### ISSUE TITLE
Polling location hours should be visible by default on mobile

### ISSUE THREAD

**Issue by cap10morgan** [votinginfoproject/vip-embeddable-tool#104]
The polling location hours are very difficult to find on mobile since they are collapsed by default. It's not obvious to users (who are in a hurry on their phones on election day) that clicking the "+" in the "Polling Location" header will reveal that information.

The hours should just be visible by default. They don't add that much height to the page and are critical pieces of information for many users.

**Comment by alexkonrad** [comment]
Updated on staging.

**Comment by agepty** [comment]
Verified.
