### ISSUE TITLE
Hide Voter ID questions if no information

### ISSUE THREAD

**Issue by jen-tolentino** [votinginfoproject/vip-embeddable-tool#109]
I want the tool to suppress the voter ID questions if there is no text included for that question. This will be really helpful for states that have recently changed their voter ID laws, but we haven't been able to confirm the information quiet yet.

**Comment by alexkonrad** [comment]
Updated on staging, but I don't have an address to test right to verify right now.

**Comment by jen-tolentino** [comment]
Can you test this KS address in staging using election ID 4100? I removed all KS voter ID information.

8508 Ensley Pl Leawood KS 66206

**Comment by alexkonrad** [comment]
Ok. I only saw the Q and A for state and then the link.

Alex Konrad

**Comment by alexkonrad** [comment]
Modifying it to remove the link if none is present. Then I'll push all these fixes to production.

**Comment by jen-tolentino** [comment]
To clarify, the questions for voter ID came up, but no answer? I just want to make sure we're hiding the questions as well if there is no data. 

Sorry if I'm missing something.

**Comment by alexkonrad** [comment]
No -- the only thing that comes up is the the field 'State', and it says
'KS'. We could remove this entirely as well if no voter id info

Alex Konrad

**Comment by jen-tolentino** [comment]
Perfect, thank you!
