### ISSUE TITLE
Pull referendum title from referendum title field

### ISSUE THREAD

**Issue by jen-tolentino** [votinginfoproject/vip-embeddable-tool#110]
The header bar for the referendum should display the referendum title field. Please see below -- this address can be tested using the staging tool.

I believe the tool was configured differently due to how states were providing data in a haphazard way prior to the general election. We are now committed to getting the data properly formatted, so it would be useful to have the tool align with the spec. Thanks!

![image](https://cloud.githubusercontent.com/assets/5825049/7054232/30858204-de09-11e4-8a95-2001d6477495.png)

**Comment by alexkonrad** [comment]
Updated on staging.

**Comment by jen-tolentino** [comment]
LGTM. Thanks!

Also -- let me know if you'd prefer to close them once you've push these changes to production, or if you'd like me to closed once I review.
