### ISSUE TITLE
Primary party text overlapping contest title

### ISSUE THREAD

**Issue by MariaDemocracyWorks** [votinginfoproject/vip-embeddable-tool#111]
In the tool, when a primary party is indicated, the italicized party name (i.e. Republican) is overlaying rather than being displayed below the office the contest is for.  See attached example.
![screen shot 2015-04-09 at 4 44 35 pm](https://cloud.githubusercontent.com/assets/7061871/7076848/4db2ef3e-deda-11e4-9604-272596c185d2.png)

**Comment by jen-tolentino** [comment]
Bump @alexkonrad @yulheecho 

This is for an election we have coming up soon, so if you could prioritize this bug fix, we'd really appreciate it. Thanks!

**Comment by alexkonrad** [comment]
Sounds good, I'll prioritize this.

Alex Konrad

**Comment by alexkonrad** [comment]
@jen-tolentino @MariaDemocracyWorks Updated.

**Comment by jen-tolentino** [comment]
Looks good, thanks Alex!
