### ISSUE TITLE
Not able to enter second address for search in IE 11

### ISSUE THREAD

**Issue by MariaDemocracyWorks** [votinginfoproject/vip-embeddable-tool#113]
A user reported, and I've since verified, that in IE 11, once you've entered an address and gotten a result, if you click on the text entry field "enter a different address," there's no way to actually enter text.  This feature works successfully in Chrome, and also in IE 10.

![pasted image at 2015_04_21 03_58 pm](https://cloud.githubusercontent.com/assets/7061871/7261540/84b47254-e840-11e4-88e5-befa5702bf9a.png)

**Comment by jen-tolentino** [comment]
@alexkonrad I just wanted to bump this. Thank you!

**Comment by alexkonrad** [comment]
Updated on staging.

**Comment by jen-tolentino** [comment]
Alex,

It looks like the issues are resolved, please push to production.

cc: @MariaDemocracyWorks 

I did want to note that some of the icons are displaying strangely in IE 11. See below, but these aren't high priority. Thank you!

![image](https://cloud.githubusercontent.com/assets/5825049/7328318/7bfd8092-eaa2-11e4-8477-e65f27fd26d1.png)

![image](https://cloud.githubusercontent.com/assets/5825049/7328349/c8fc27e0-eaa2-11e4-9121-cdb33ed785a8.png)

**Comment by alexkonrad** [comment]
Ok, will look into this.

Alex Konrad

**Comment by alexkonrad** [comment]
This is updated on staging. IE treats SVG images a little differently so I redid the icons.

**Comment by jen-tolentino** [comment]
LGTM. Thanks!
