### ISSUE TITLE
Line break characters don't seem to be respected in referendum text.

### ISSUE THREAD

**Issue by MariaDemocracyWorks** [votinginfoproject/vip-embeddable-tool#114]
In referendum text, states are often invested in having the language presented in a format that reflects the way it's laid out on their ballots. Commonly, this involves line breaks. 

For example, for one referenda, the XML is structured like this:

<referendum id="53110560111205">
  <title>Tumwater Transportation Benefit District, Proposition No. 1, Sales and Use Tax for Transportation Improvements</title>
  <text>The Tumwater City Council, serving as the Board of the Tumwater Transportation Benefit District, Tumwater, Washington, adopted Resolution R2015-002 concerning a sales and use tax to fund transportation improvements within the District. This proposition would approve a two-tenths of one percent (0.2%) sales and use tax to be collected for ten years. Revenues would fund a repair, maintenance and improvement program for existing city streets and associated infrastructure including rebuilding, repaving, sealing, patching and other methods to improve and extend the life of pavement, bridges, drainage facilities and pedestrian improvements including repair or replacement of sidewalks and construction of curb ramps in conjunction with authorized pavement work.&#xA; Tumwater's Proposition 1 is a proposal for funding improvements to Tumwater's streets and sidewalks.    As federal and state grant money shrinks, we must raise money locally to preserve our streets and sidewalks. By increasing the city's portion of sales tax by two tenths of one percent (.002) on retail sales, an estimated $810,000 per year of revenue will be dedicated to much needed maintenance and repairs to Tumwater's streets. The cost is small - just 2 cents on a $10 purchase or just $1 on a $500 TV. Groceries are not subject to sales tax so this won't increase your food bill.&#xA; We all know our streets and sidewalks are in need of repair. Any tax increase should be a thoughtful decision by those who it affects. With the extensive retail sector in Tumwater, this small sales tax increase would be paid by a majority of the users of our city streets and roads as they drive to Tumwater to shop. In this way, the funding is shared, not just collected from Tumwater residents and businesses. The funds raised by this proposition can only be used to maintain and repair existing streets and sidewalks; they cannot be used to subsidize new development.&#xA; Well maintained streets and sidewalks not only connect our community and make our streets safer, they benefit our businesses, and help our police and fire departments respond to emergencies faster.&#xA; Please support Tumwater's Proposition 1 and vote yes to maintain and improve Tumwater's streets and sidewalks. &#xA; REBUTTAL OF ARGUMENT AGAINST:&#xA; By law, this tax can only last for 10 years and cannot be extended without another public vote.&#xA; Tumwater aggressively manages its finances with a "tighten the belt" mentality and continues to search for ways to shift resources and reduce costs. Street maintenance costs are too high to manage within existing resources.  In the past Tumwater received significant state and federal grant money to help pay for street maintenance. Those funds are no longer available. &#xA;   FOR MORE INFORMATION:&#xA; https://weiapplets.sos.wa.gov/myvote/onlinevotersguide/Measures?electionid=56&amp;countycode=TH, Sales tax increases have an unfair and disproportionate impact on our poorest families:&#xA; According to the Institute on Taxation and Economic Policy, Washington [already] has the most unfair local and state tax system in the country, with the bottom 20% of our families already paying 16.8% of their income toward existing State &amp; Local Taxes. An additional local sales tax increase will only further increase the disparity between wealthy and poor families' taxes as a percentage of income.&#xA; Existing revenue sources ought to be sufficient for maintenance and improvement of streets and sidewalks:&#xA; In Tumwater's nearly 150 year history, it has managed to maintain its streets and sidewalks without the burden of this new tax. As taxpaying citizens and families, we all know the difficulty of budgeting in the face of declining incomes and growing expenses. Unlike our municipality, however, we don't have the luxury of taxing our way into a balanced budget. Rather, we've had to "tighten our belts" and adjust the priorities of our expenses to match our income. As citizens, it is our duty to hold our government to the same standards to which we hold ourselves - which means reducing inessential expenses in favor of more critical items like infrastructure maintenance.&#xA; There is no "end-date" to this tax increase:&#xA; Without predefined funding goals, this tax increase will exist in perpetuity. Long after State and Federal infrastructure funding returns to normal levels, your children will still be paying this sales tax with no end in sight.&#xA; REBUTTAL OF ARGUMENT AGAINST:&#xA; Even one year of new taxes ($810,000) is a lot of money to siphon out of Tumwater businesses and families' budgets, let alone $8.1 million over 10 years. Sure "food" will be exempt, but the rest of our grocery bills? Prices of everything from toothpaste to diapers will go up - hitting our families where it hurts the most: our wallets.&#xA; Voting "No" sends a clear message to City leaders: don't tax more - spend less!&#xA; FOR MORE INFORMATION: https://weiapplets.sos.wa.gov/myvote/onlinevotersguide/Measures?electionid=56&amp;countycode=TH</text>

When test address 1200 SW Bay Street, Tumwater, WA 98512, is searched in the tool, the referenda displays in one solid block of text. 

![screen shot 2015-04-22 at 11 09 43 am](https://cloud.githubusercontent.com/assets/7061871/7277903/7768de32-e8e0-11e4-988d-8bb633989a97.png)

Is there a modification we could make so that line breaks could be displayed in the tool?

**Comment by jen-tolentino** [comment]
@alexkonrad @yulheecho 

It would be great if this could be prioritized, since this was identified by an election official for an upcoming election. If something that can be changed quickly, or if you can tell us whether there is a specific character we should be including for line breaks, that would be very helpful.

**Comment by alexkonrad** [comment]
Updated on staging to differentiate the title and the subtitle (body of
text). If this is the desired result I can move it over to production.
Please review!

Alex Konrad

**Comment by MariaDemocracyWorks** [comment]
@alexkonrad @jen-tolentino 

While differentiating title and subtitle would be helpful, this is actually a separate issue.  I realize that my earlier issue report probably wasn't very useful, since github didn't retain the XML new line characters in the pasted text.

States sometimes include line breaks in the referendum text itself, especially if the referenda is especially long, like these examples in Washington, to create new paragraphs and provide readability.  

![screen shot 2015-04-22 at 6 47 21 pm](https://cloud.githubusercontent.com/assets/7061871/7287151/0f397ec6-e920-11e4-9d62-bdc7823e7340.png)

The xml uses the characters "&#xA;" to indicate a line break in the text, and I was wondering if that was something the tool could handle, or if there was any other acceptable way of handling line breaks in this context.

**Comment by alexkonrad** [comment]
It looks like those XML newline characters are being converted into new
lines in the HTML source (which isn't interpreted as a newline by the
browser). We can work on converting this character at the browser-level
rather than the source-level.

Alex Konrad

**Comment by alexkonrad** [comment]
Updated. Please let me know if there are additional HTML/XML entity
characters that you would like to see converted for presentation (we have
to do them on a case-by-case basis). Thanks!

Alex Konrad

**Comment by MariaDemocracyWorks** [comment]
I'm not seeing a change, Alex.  Should this be visible in the tool now? @jen-tolentino @alexkonrad

**Comment by alexkonrad** [comment]
@MariaDemocracyWorks This should be here: http://s3.amazonaws.com/vip-voter-information-tool-staging/staging.html

I tried with 1200 bay st southwest tumwater wa

**Comment by alexkonrad** [comment]
My javascript was cached so I had to clear cache. Let me know if it's not updated or needs more work.

**Comment by MariaDemocracyWorks** [comment]
That looks great, Alex!  When will those changes be visible in the live tool?

**Comment by alexkonrad** [comment]
I'm hoping to bundle this and updates to some of the more critical bugs
together for a push this afternoon.

Alex Konrad

**Comment by jen-tolentino** [comment]
Thanks Alex!
