### ISSUE TITLE
Title of referendum is also displaying in body text

### ISSUE THREAD

**Issue by jen-tolentino** [votinginfoproject/vip-embeddable-tool#115]
The title should not be duplicated in the body of the text, please see example from staging below for "Paris Unincorporated Area Tax Levy," which should only display in the header.

Thank you!
cc: @pstenbjorn
![image](https://cloud.githubusercontent.com/assets/5825049/7323410/50885336-ea7c-11e4-921b-bc06d00454b5.png)

**Comment by alexkonrad** [comment]
@jen-tolentino For this one, "Paris Unincorporated Area Tax Levy" is both the office and the referendum title, so if I put the referendum title on the header it will just repeat twice. I could (a) show both, (b) prefer the office over the referendum title, or (c) prefer the referendum title over the office. Are they mutually exclusive? ie, is there only ever an office or a referendum title?

**Comment by pstenbjorn** [comment]
Alex,

I would favor the referendum title over the contest.office for display.

Thanks,

Paul

**Comment by alexkonrad** [comment]
Updated on staging.

**Comment by jen-tolentino** [comment]
Looks great! Thank you.
