### ISSUE TITLE
Office name not displaying in header

### ISSUE THREAD

**Issue by jen-tolentino** [votinginfoproject/vip-embeddable-tool#117]
This may be related to the recent fix for #115 

The office name is not displaying in the header section:
![image](https://cloud.githubusercontent.com/assets/5825049/7355456/ffaa6eba-ecef-11e4-950c-cb4e51779d21.png)

cc:@nomadaisy

**Comment by alexkonrad** [comment]
Updated on staging and live.

Alex Konrad

**Comment by jen-tolentino** [comment]
Thank you!
