### ISSUE TITLE
Staging tool not working for WA Special Election

### ISSUE THREAD

**Issue by kthale** [votinginfoproject/vip-embeddable-tool#118]
The staging tool is not functioning for Washington's Special Election occurring tomorrow (4/28). When any address is entered it goes to a blank screen. Can you please check out this high-priority bug ASAP? 

Thank you.

**Comment by alexkonrad** [comment]
Can you give a sample address?

Alex Konrad

**Comment by alexkonrad** [comment]
Or an address that can replicate this behavior @kthale

**Comment by kthale** [comment]
Try this one: 1634 S Lane St, Seattle, WA

The "Mail-In Voting State" dialogue box pops up, and you select, "Continue." Upon doing so, you get a blank screen.

@alexkonrad

**Comment by alexkonrad** [comment]
Got it, thank you.

Alex Konrad

**Comment by alexkonrad** [comment]
Updated. Please clear your cache and check that same address. Thanks!

Alex Konrad

**Comment by kthale** [comment]
It's working now. Thanks so much, Alex. I appreciate your help on this!
