### ISSUE TITLE
Display candidate email and phone number when available

### ISSUE THREAD

**Issue by jen-tolentino** [votinginfoproject/vip-embeddable-tool#119]
The live MI data (1413 Begole St, Flint, MI 48503) includes additional contact information, such as phone number and email address, that we'd like to have displayed in the tool when available.

Thanks!

**Comment by alexkonrad** [comment]
For this one I'm only seeing phone # in the live API response data but I'm
working on including email address too

Alex Konrad

**Comment by jen-tolentino** [comment]
Interesting. When I checked the live data all the candidates but "BARRY L. WILLIAMS" had an email addresses associated.

**Comment by alexkonrad** [comment]
Ok, got it. I thought you meant phone numbers and emails for the election
officials. Thanks!

Alex Konrad

**Comment by alexkonrad** [comment]
This is updated on staging. Let me know if you want to redo the formatting for candidates in these cases.

**Comment by jen-tolentino** [comment]
Thanks Alex! 

We hope to eventually receive more contact information for candidates (social media accounts, etc.) so it might be more readable in the long-term if this information was displayed as icons. Is that a possibility?

**Comment by jen-tolentino** [comment]
Alex -- this changed has been pushed to production, but the request for displaying icons rather than complete information was not addresses. Let me know if this is something we can do, or if it would be a significant time investment so we can discuss alternatives.

Thanks!

**Comment by alexkonrad** [comment]
@jen-tolentino We can do this, it's just a matter of how you want the information displayed and hidden (for example, a hover over, click, etc). I'm not sure how it would look with an icon, but maybe we can talk about that on the call tomorrow.

**Comment by alexkonrad** [comment]
Updated on staging.

**Comment by jen-tolentino** [comment]
Hey Alex, the staging tool actually doesn't seem to be pulling up any results (specifically trying EID4100). I double checked the API key, which is still fine, so I'm not sure what might have happened.

**Comment by alexkonrad** [comment]
These both seem to work for me:

http://s3.amazonaws.com/vip-voter-information-tool-staging/stagingElection4100.html
http://s3.amazonaws.com/vip-voter-information-tool-staging/configurable.html

I believe the original 'staging' instance pulls staging data from the next upcoming election, not the test election 4100. I'll look into it, let me know if it's still not working.

**Comment by agepty** [comment]
Verified.
