### ISSUE TITLE
Maintain text casing from the Google API

### ISSUE THREAD

**Issue by nomadaisy** [votinginfoproject/vip-embeddable-tool#120]
Currently, the tool upper cases each word in text fields. Can we remove automatic casing of any text? The Google automatic casing should take care of casing in instances where the text is all lower case. 

For example, LA submitted data in which their Early Vote Site days_times_open was submitted as:
    8:30 a.m. to 6 p.m. on early voting days. Closed on Sundays.

The tool changes this to:
    8:30 A.M. To 6 P.M. On Early Voting Days. Closed On Sundays.

Thank you!

**Comment by jen-tolentino** [comment]
I just wanted to bump this @alexkonrad Thank you!

**Comment by alexkonrad** [comment]
@jen-tolentino Is there a specific LA address we can use for testing? Thanks!

**Comment by nomadaisy** [comment]
An example test address:

130 Vital St
Layfayette, LA 70506

Thanks!

**Comment by alexkonrad** [comment]
Updated.

Alex Konrad

**Comment by jen-tolentino** [comment]
Thank you!
