### ISSUE TITLE
No error message displays for address with no election information, when switching addresses in the tool

### ISSUE THREAD

**Issue by jen-tolentino** [votinginfoproject/vip-embeddable-tool#121]
If a user switches the address while in the tool, to an address that does not result in election information, no error message comes up. It just seems like the tool didn't accept the address.

You can test this address (its live data): 1220 N Orange Grove Ave
West Hollywood, CA 90046

And then try to switch with enter another non-West Hollywood address (pretty much any address in the U.S. right now will not display results in a live tool)

**Comment by alexkonrad** [comment]
Updated in staging.

**Comment by agepty** [comment]
Verified.
