### ISSUE TITLE
URGENT: Ballot info & Voter Resources tabs not loading data in IE 11

### ISSUE THREAD

**Issue by MariaDemocracyWorks** [votinginfoproject/vip-embeddable-tool#123]
@jen-tolentino 

The City of West Hollywood alerted us to an issue where when a user loads the tool embedded on their website in IE11 and performs a search, the polling place result loads correctly, but no data loads on the Ballot Information and Voter Resources tabs.  The same address loads results on all tabs when the same copy of the tool is viewed using Chrome.  

I've confirmed that this is issue is not specific to the embed at http://www.weho.org/city-hall/city-clerk/election-information/voter-tool-test and occurs on all versions of the tool.

Since they've embedded the tool on their website and are publicizing it in advance of their June 2nd election, it would be great to get this corrected as soon as possible.  Thank you!
![ballot-information](https://cloud.githubusercontent.com/assets/7061871/7759955/561f9eda-ffe4-11e4-835f-9add3b66191c.PNG)
![resources](https://cloud.githubusercontent.com/assets/7061871/7759956/58947ea6-ffe4-11e4-8193-40dc94cb5f8a.PNG)

**Comment by alexkonrad** [comment]
I'll prioritize this.

Alex Konrad

**Comment by jen-tolentino** [comment]
@alexkonrad I hope you had a great holiday weekend. I just wanted to bump this, as @MariaDemocracyWorks mentioned, this was a bug flagged by an election official for an upcoming election.

Thank you!

**Comment by jen-tolentino** [comment]
@alexkonrad Can you provide an estimate for when this bug might be addressed? That'll helpful us message the problem to state partners.

**Comment by alexkonrad** [comment]
Jen,

I just pushed up a fix, but something is wrong with the tab icons so I'm
looking into that now. In the meantime, it worked on our IE 11 testing
instances so you may want to test on your own environments.

Alex Konrad

**Comment by jen-tolentino** [comment]
Thanks Alex! The ballot tab is working in IE 11 again, although the voter resources tab is a little weird (see below).

![image](https://cloud.githubusercontent.com/assets/5825049/7823537/21f270b2-03ca-11e5-9511-78952d4d740e.png)

**Comment by alexkonrad** [comment]
Updated.

Alex Konrad

**Comment by jen-tolentino** [comment]
Looks great, thank you!
