### ISSUE TITLE
Searched addresses displaying in all lowercase

### ISSUE THREAD

**Issue by MariaDemocracyWorks** [votinginfoproject/vip-embeddable-tool#124]
@jen-tolentino 
State users are pointing out that the searched "Registered Address" is displaying in lowercase for the street and city, regardless of how it was entered by the user. 
![screen shot 2015-05-22 at 12 18 12 pm](https://cloud.githubusercontent.com/assets/7061871/7774937/da8d4b2a-007c-11e5-8ede-6a0fa3a276ee.png)

If it's possible to proper case those parts of the address, that would be helpful.

**Comment by MariaDemocracyWorks** [comment]
![image](https://cloud.githubusercontent.com/assets/7061871/7775446/3a1a3bc6-0081-11e5-8420-0a9faea06f52.png)

In case this is useful,this used to be the way the tool displayed the searched address.  If we can undo this change, that would be great.

**Comment by alexkonrad** [comment]
This appears to be a change in how the API normalizes the entered address.
I'll add a capitalizing function to the tool.

Alex Konrad

**Comment by jen-tolentino** [comment]
Alex, thanks for looking into this. Since its a function of the API, let's put this on hold until we can confirm with Google that this isn't a bug.

**Comment by alexkonrad** [comment]
Closing this because we've established it's the API and opened up a related enhancement (#125).
