### ISSUE TITLE
Upper-case the first letter of user's address

### ISSUE THREAD

**Issue by jen-tolentino** [votinginfoproject/vip-embeddable-tool#125]
The address entered by a user comes back from the Google Civic API with will casing removed. Please including functionality to upper-case the first letter of the user's address. Let me know if its not possible to isolate this functionality to the user's address, or if it must be (or is significantly easier to do so) across the entire tool,

Thanks!

**Comment by alexkonrad** [comment]
Updated.

**Comment by jen-tolentino** [comment]
Looks good, thanks.
