### ISSUE TITLE
[iOS] User unable to COPY CODE / EMAIL CODE

### ISSUE THREAD

**Issue by agepty** [votinginfoproject/vip-embeddable-tool#126]
While using an iOS device, user notices that via Step 8, the COPY CODE and EMAIL CODE function do not work.  

INTENDED CODE BELOW:
>  <div id="embed-code" class="row text-box copy-code">&lt;script type="text/javascript" src="//s3.amazonaws.com/vip-voter-information-tool/app.js"&gt;&lt;/script&gt;
&lt;div id="_vit"&gt;&lt;/div&gt;
&lt;script type="text/javascript"&gt;vit.load({<br><span>    modal: true,</span><br ng-if="selectedTheme != '' &amp;&amp; selectedTheme != 'No Theme'" class="ng-scope"><span ng-if="selectedTheme != '' &amp;&amp; selectedTheme != 'No Theme'" class="ng-binding ng-scope">    theme: 'https://s3.amazonaws.com/vip-voter-information-tool/images/theme2.png',</span><br><span ng-if="title" class="ng-binding ng-scope">    title: dummy Police</span><br ng-if="title" class="ng-scope"><span ng-if="subtitle" class="ng-binding ng-scope">    subtitle: Ring ring dummy police?</span><br ng-if="subtitle" class="ng-scope"><br ng-if="selectedFormat.length &gt; 0" class="ng-scope"><span ng-if="selectedLogoOption == 'Logo'" class="ng-binding ng-scope">    logo: 'http://img2.wikia.nocookie.net/__cb20120913022452/adventuretimewithfinnandjake/images/3/3f/Talking_Bush.PNG',</span><br ng-if="selectedLogoOption == 'Logo'" class="ng-scope"><span ng-if="selectedTileBarColor" class="ng-binding ng-scope">    colors: {
      'header': '#9ccc66',
      'landscapeBackgroundHeader': '#7caa66'
    },</span><br ng-if="selectedTileBarColor" class="ng-scope"><span ng-if="alertTextEnabled" class="ng-binding ng-scope">    alertText: 'There's a dummy in my yard'</span><br ng-if="alertTextEnabled" class="ng-scope"><span ng-if="selectedLanguage" class="ng-binding ng-scope">    language: 'ja'</span><br ng-if="selectedLanguage" class="ng-scope">});&lt;/script&gt;</div>

**Comment by mickeysanchez** [comment]
Ready to retest, i decided to hide copy code on iOS mobile safari devices because i can't find a solution for copy to clipboard right now. Email is working now however.

**Comment by agepty** [comment]
Verified.
