### ISSUE TITLE
[Android] Keyboard pushes content on screen

### ISSUE THREAD

**Issue by agepty** [votinginfoproject/vip-embeddable-tool#127]
While using an Android device, the user notices that the keyboard pushes content on screen, when pulled up.

![screen shot 2015-07-07 at 11 37 38 am](https://cloud.githubusercontent.com/assets/10159083/8555618/41a6497c-24bf-11e5-9b1f-64550207f6ea.png)

**Comment by mickeysanchez** [comment]
ready for retest.

**Comment by agepty** [comment]
Verified.
