### ISSUE TITLE
[Mobile > Landscape Mode] Content on page does not scale for smaller screens

### ISSUE THREAD

**Issue by agepty** [votinginfoproject/vip-embeddable-tool#128]
While viewing the site, via mobile > landscape mode, the user notices that the content on the page does not scale.

![screenshot_2015-07-07-15-25-27](https://cloud.githubusercontent.com/assets/10159083/8555659/767880ca-24bf-11e5-853e-07897478298f.png)

**Comment by mickeysanchez** [comment]
Ready for restest - changed break point to 685px

**Comment by agepty** [comment]
User can't scroll on the pages now 

![screen shot 2015-07-08 at 3 34 29 pm](https://cloud.githubusercontent.com/assets/10159083/8580159/f94cf64e-2586-11e5-8c0b-3c6561c429c8.png)

**Comment by mickeysanchez** [comment]
What devices?

**Comment by agepty** [comment]
Checking on S5

iPhone 6 has display issues on there other steps - but I want to square this away first and then open another issue - once S5 can be tested.

**Comment by mickeysanchez** [comment]
Can we close this and open a new issue about how to handle landscape on phone?

**Comment by agepty** [comment]
Closing and opening new issue.
