### ISSUE TITLE
[Text Fields] No min / max character count implemented

### ISSUE THREAD

**Issue by agepty** [votinginfoproject/vip-embeddable-tool#129]
While viewing the site, the user notices that there is no min / max character count implemented. 

This could cause issues with a large amount of copy.

*Seen on the following*:
- Title
- Subtitle
- Alert Message

**Comment by mickeysanchez** [comment]
I don't think I will be implementing this, as of now the title, subtitle, and alert message all wrap when they reach the end of a line, allowing for text that is quite long.
