### ISSUE TITLE
[Embed Code] Comma not implemented after Alert Message code

### ISSUE THREAD

**Issue by agepty** [votinginfoproject/vip-embeddable-tool#130]
While viewing the following code, the user notices that there is no comma after the alertText, so the code therefore fails, and does not display correctly.

<img width="1178" alt="screen shot 2015-07-07 at 3 57 07 pm" src="https://cloud.githubusercontent.com/assets/10159083/8555858/d71b82d2-24c0-11e5-9d10-7e51f8d3e8ac.png">

**Comment by mickeysanchez** [comment]
Ready for re-test

**Comment by agepty** [comment]
Verified.
