### ISSUE TITLE
[Copy Code Button] Feedback should be seen

### ISSUE THREAD

**Issue by agepty** [votinginfoproject/vip-embeddable-tool#131]
When the user clicks the COPY CODE button, via last step, there should be some feedback seen from the site, whether a pop-up prompt or text box with alert saying code copied.

**Comment by mickeysanchez** [comment]
I added a click and hover state think that should be enough. Not sure we need a pop up or anything like that.

**Comment by agepty** [comment]
COPY option is now removed.
