### ISSUE TITLE
[iPhone 6] Preview: Display issue with Title section

### ISSUE THREAD

**Issue by agepty** [votinginfoproject/vip-embeddable-tool#132]
While viewing the site, the user notices that the Title section for the preview is not seen correctly 

![img_0066-2](https://cloud.githubusercontent.com/assets/10159083/8574718/285d4a18-2566-11e5-8504-428cb805c96a.png)

**Comment by mickeysanchez** [comment]
REady for retest.

**Comment by agepty** [comment]
Verified.
