### ISSUE TITLE
[Preview] No Theme has image error

### ISSUE THREAD

**Issue by agepty** [votinginfoproject/vip-embeddable-tool#133]
While viewing the preview - the user notices that the NO THEME option shows an error within the preview.

![img_0065](https://cloud.githubusercontent.com/assets/10159083/8574862/dbf3e3b6-2566-11e5-91ac-cf4ac7d071d9.png)

**Comment by mickeysanchez** [comment]
Ready for re-test

**Comment by agepty** [comment]
Verified.
