### ISSUE TITLE
[240 px View] Footer overlaps body copy

### ISSUE THREAD

**Issue by agepty** [votinginfoproject/vip-embeddable-tool#134]
While viewing the 240px view, the footer overlaps the copy from the body.

<img width="417" alt="screen shot 2015-07-08 at 12 49 08 pm" src="https://cloud.githubusercontent.com/assets/10159083/8576462/49534ad8-2570-11e5-9e41-043f35c79bf4.png">

**Comment by alexkonrad** [comment]
Updated on staging.

**Comment by agepty** [comment]
Verified.
