### ISSUE TITLE
[FF] State Logos: States are missing imagery 

### ISSUE THREAD

**Issue by agepty** [votinginfoproject/vip-embeddable-tool#135]
While viewing site, via FF, the user notices that the State Logos for the following states are missing imagery.

- California - is missing
- Delaware - is missing
- Florida - is missing
- Georgia - is missing
- Hawaii - is missing
- Idaho - is missing
- Kansas - is missing 
- Michigan - is missing
- Missouri - is missing 
- New Hampshire - is missing
- New Jersey - is missing
- New York - is missing 
- Vermont - is missing
- Virginia - is missing

**Comment by mickeysanchez** [comment]
Ready for retest.

**Comment by agepty** [comment]
Verified.
