### ISSUE TITLE
[State Logo] Connecticut imagery is not displayed correctly

### ISSUE THREAD

**Issue by agepty** [votinginfoproject/vip-embeddable-tool#136]
While viewing the State Logo for Connecticut, the user notices that the imagery is not displayed correctly.

<img width="443" alt="screen shot 2015-07-08 at 12 40 41 pm" src="https://cloud.githubusercontent.com/assets/10159083/8576569/f860de3c-2570-11e5-81f0-32aef6b566d1.png">

**Comment by mickeysanchez** [comment]
I also thought this was an issue, but turns out that that's the shape of the Connecticut state logo.

**Comment by agepty** [comment]
As per @mickeysanchez comment - closing this
