### ISSUE TITLE
[IE 10 / 11] Preview doesn't display theme on tablet or mobile preview image

### ISSUE THREAD

**Issue by agepty** [votinginfoproject/vip-embeddable-tool#137]
While viewing site, via IE 10 / 11, the user notices that there are display issues 

- Checkbox bubbles are not displaying selections next to checkbox 
![screen shot 2015-07-08 at 3 05 49 pm](https://cloud.githubusercontent.com/assets/10159083/8579683/08c69100-2584-11e5-9e1a-303be5ee0f63.png)

- Dropdown menus are not displayed correctly
![screen shot 2015-07-08 at 3 05 31 pm](https://cloud.githubusercontent.com/assets/10159083/8579675/0298c1f4-2584-11e5-93a6-d318d5f729a3.png)

- Theme preview is not displaying on Tablet / Mobile
![ie10_-_win7__snapshot_1___running_ 2](https://cloud.githubusercontent.com/assets/10159083/8579689/1e46f538-2584-11e5-9ad2-be59385cc561.png)
![ie10_-_win7__snapshot_1___running_](https://cloud.githubusercontent.com/assets/10159083/8579690/1e4b2662-2584-11e5-85c9-c82f4519452c.png)

- Color selector does not display
![screen_shot_2015-07-08_at_3_05_31_pm](https://cloud.githubusercontent.com/assets/10159083/8580019/2ade272e-2586-11e5-9ed5-79bd0448dfbf.png)

**Comment by mickeysanchez** [comment]
Fixed all issues except one - changed title

**Comment by mickeysanchez** [comment]
fixed that last issue - ready for re-test.

**Comment by agepty** [comment]
Verified.
