### ISSUE TITLE
Lock orientation issue with android keyboard.

### ISSUE THREAD

**Issue by agepty** [votinginfoproject/vip-embeddable-tool#139]
While viewing the site, via mobile > landscape mode, the user notices that the he can not scroll on pages.

![f94cf64e-2586-11e5-8c0b-3c6561c429c8](https://cloud.githubusercontent.com/assets/10159083/8597538/033b33ee-2624-11e5-935b-1f9dbcf256e1.png)

**Comment by mickeysanchez** [comment]
Ready for retest - decided to fake a locked orientation.

**Comment by agepty** [comment]
While attempting to type in text fields, now the orientation of the page as well goes horizontal.

![screenshot_2015-07-21-15-51-56](https://cloud.githubusercontent.com/assets/10159083/8811107/7faab1e2-2fc1-11e5-81b2-2911e85d7618.png)

**Comment by mickeysanchez** [comment]
fixed

**Comment by agepty** [comment]
Verified.
