### ISSUE TITLE
[Mobile] Preview - Default is Desktop, however shows Tablet preview

### ISSUE THREAD

**Issue by agepty** [votinginfoproject/vip-embeddable-tool#140]
While viewing the preview panel for the first step, the user notices that the preview default is desktop however the preview panel is showing tablet as the preview.

![img_0072](https://cloud.githubusercontent.com/assets/10159083/8659256/7f9198c4-2977-11e5-843b-90a152f8a700.PNG)

**Comment by mickeysanchez** [comment]
ready to restest

**Comment by agepty** [comment]
Verified.
