### ISSUE TITLE
Custom Logo link is not included in preview or final code 

### ISSUE THREAD

**Issue by jen-tolentino** [votinginfoproject/vip-embeddable-tool#143]
When selecting and linking to a custom logo, there is no verification that the link works (if this isn't possible we should probably include a note that custom logos will not be displayed in in the preview). 

Further, when linking to a logo, it did not seem to appear in the final code.

![image](https://cloud.githubusercontent.com/assets/5825049/8735528/88c3f51c-2bdf-11e5-8b32-6da9978fc8fb.png)

![image](https://cloud.githubusercontent.com/assets/5825049/8735540/99a67922-2bdf-11e5-9dfc-8a54caff78b5.png)

**Comment by mickeysanchez** [comment]
added.

**Comment by agepty** [comment]
Verified.
