### ISSUE TITLE
Text within CTA is not aligned within the button

### ISSUE THREAD

**Issue by agepty** [votinginfoproject/vip-embeddable-tool#145]
While viewing the site, the user notices that the text within the CTA is not aligned correctly.

The spacing on the left side is more than the right side of the text.

<img width="382" alt="screen shot 2015-07-21 at 3 47 40 pm" src="https://cloud.githubusercontent.com/assets/10159083/8810845/d58d6f20-2fbf-11e5-8d8c-f51db631d7ec.png">

**Comment by mickeysanchez** [comment]
fixed

**Comment by agepty** [comment]
Verified.
