### ISSUE TITLE
[Mobile] Preview: Using Theme One with Logo, displays logo too high on preview

### ISSUE THREAD

**Issue by agepty** [votinginfoproject/vip-embeddable-tool#146]
While viewing the Preview, for Theme One, the user notices that the logo is displayed too high on the page, that it overlaps the stripes at the top of the page.

![screenshot_2015-07-21-15-50-06](https://cloud.githubusercontent.com/assets/10159083/8811161/09c41a76-2fc2-11e5-9b96-f568a6f46e61.png)

NOTE: Seen for all preview options (Desktop, Tablet, and Mobile)

**Comment by mickeysanchez** [comment]
fixed

**Comment by agepty** [comment]
Verified.
