### ISSUE TITLE
[IE 10] State Seals are not seen 

### ISSUE THREAD

**Issue by agepty** [votinginfoproject/vip-embeddable-tool#147]
While viewing the site, the user notices that there are no state seals seen.

![screen shot 2015-07-21 at 4 13 28 pm](https://cloud.githubusercontent.com/assets/10159083/8811343/7683f770-2fc3-11e5-91b9-3d9828a66210.png)

**Comment by mickeysanchez** [comment]
Cannot reproduce. Windows version?

**Comment by mickeysanchez** [comment]
Oh wait, looks like its only certain states.

**Comment by agepty** [comment]
California - is missing
Delaware - is missing
Florida - is missing
Georgia - is missing
Hawaii - is missing
Idaho - is missing
Kansas - is missing
Michigan - is missing
Missouri - is missing
New Hampshire - is missing
New Jersey - is missing
New York - is missing
Vermont - is missing
Virginia - is missing

**Comment by mickeysanchez** [comment]
fixed.

**Comment by agepty** [comment]
Verified.
