### ISSUE TITLE
Embed Code: Title / Subtitle are missing ' and , in code

### ISSUE THREAD

**Issue by agepty** [votinginfoproject/vip-embeddable-tool#148]
While viewing the Embed Code, the user notices that there are no single quotation marks around the copy nor is there a comma at the end of the code.

![screen shot 2015-07-21 at 4 33 58 pm](https://cloud.githubusercontent.com/assets/10159083/8811795/54c18f14-2fc6-11e5-9f56-9b79b85fca3f.png)

**Comment by mickeysanchez** [comment]
fixed

**Comment by agepty** [comment]
Verified.
