### ISSUE TITLE
[API modification] display additional referendum data

### ISSUE THREAD

**Issue by jen-tolentino** [votinginfoproject/vip-embeddable-tool#150]
**Please prioritize this request**

The Google Civic API was recently modified to display additional referendum data. Previously, the API only provided referendumTitle and referendumSubtitle. There are now several additional fields that could possibly be displayed if data is available (https://developers.google.com/civic-information/docs/v2/elections/voterInfoQuery).

Desired functionality: Display data for all available referendum fields
Test address in staging: 726 4th Ave SW, Puyallup, WA 98371

cc :@MariaDemocracyWorks

**Comment by jen-tolentino** [comment]
@yulheecho As we discussed on our call yesterday, we'd really like this to be done as soon as possible. Please let me know what a feasible timeline for your team looks like for this. Thanks!

**Comment by alexkonrad** [comment]
We're hoping to have this done by the end of the day today. I'll update
when it's ready for testing

Alex Konrad

**Comment by jen-tolentino** [comment]
Awesome, thank you so much Alex!

**Comment by alexkonrad** [comment]
Jen, it should be updated on staging and live. Right now we're just going down the list of fields and displaying any / all, but let me know if there's a different order or some other formatting that we should build in. It should also preserve the original formatting within a field like we discussed for the other issue.

**Comment by jen-tolentino** [comment]
This looks great! I think displaying everything should work, but if we hear back from the states that we need to make any modifications, I'll file a new issue.
