### ISSUE TITLE
Kansas State Seal Stretched on Embed

### ISSUE THREAD

**Issue by kthale** [votinginfoproject/vip-embeddable-tool#151]
The state seal for Kansas is distorted for current live embed. 

![knss_embed](https://cloud.githubusercontent.com/assets/3733857/9009116/f7be06ae-376c-11e5-846d-99e1d10cbccd.png)

Also, please see embed here: http://www.knssradio.com/pages/21782394.php

**Comment by alexkonrad** [comment]
Updated. The embed on knssradio.com looks correct now.
