### ISSUE TITLE
Image on address entry page not sizing responsively.

### ISSUE THREAD

**Issue by MariaDemocracyWorks** [votinginfoproject/vip-embeddable-tool#152]
I noticed that when you view the embeddable tool on a webpage on a mobile phone (iphone 5) the image on the address entry page isn't sizing correctly, and so is showing up with the title partially cut off.

![img_2150](https://cloud.githubusercontent.com/assets/7061871/9092827/815fd6f0-3b76-11e5-87fd-8db7a449be41.PNG)

**Comment by alexkonrad** [comment]
Updated.
