### ISSUE TITLE
Ballot tab is displaying when no ballot data is present

### ISSUE THREAD

**Issue by jen-tolentino** [votinginfoproject/vip-embeddable-tool#153]
The ballot tab is usually hidden when no ballot data is provided by the Google API; however, it is display and simply blank for this address: 3322 S HUNTER VILLAGE DR WEST VALLEY UT 84128-2635

FYI this is live election data that will expire today.

![image](https://cloud.githubusercontent.com/assets/5825049/9202878/f1a19138-4021-11e5-9569-fb75e6b8a09c.png)

**Comment by alexkonrad** [comment]
Updated.
