### ISSUE TITLE
Alert and logo overlap in customizer preview

### ISSUE THREAD

**Issue by jen-tolentino** [votinginfoproject/vip-embeddable-tool#154]
When viewing the preview for an alert through the customizer, the logo displays front of the alert. Since this isn't how it would display, can you adjust the sizing to eliminate confusion?

![image](https://cloud.githubusercontent.com/assets/5825049/9274134/f5d09e52-4260-11e5-8095-cca4beafbfad.png)

**Comment by alexkonrad** [comment]
@jen-tolentino we swapped the logos from being SVG tags like the rest of the device preview to just being regular HTML image tags because of display issues with certain SVG state seals, which explains the layering here. We'll have to look into a way to layer the alert text on top of the image without reintroducing those state seal display issues.

**Comment by mickeysanchez** [comment]
fixed

**Comment by jen-tolentino** [comment]
Thanks Mickey, but now the logo is hidden. Is there any way to adjust the spacing so that both are properly spaced in the preview? If not, we may need to add language that makes it clear that the alert and logo will be visible.

![image](https://cloud.githubusercontent.com/assets/5825049/9336514/f94770ac-45a7-11e5-828f-537f25adb621.png)

**Comment by mickeysanchez** [comment]
Jen, this is what it looks like in the actual tool:

![pasted image at 2015_08_25 10_57 am](https://cloud.githubusercontent.com/assets/4680863/9470064/2b86115c-4b18-11e5-8e01-8729bff509e4.png)

So they actually do overlap. Do you think it would be a better fix to make the alert in the customizer translucent, like the real thing, and perhaps add a message that tells the user of the custormizer that the alert disappears after a few seconds?

**Comment by jen-tolentino** [comment]
Mickey, you're completely right and I think that's a great solution. Thank you!

**Comment by mickeysanchez** [comment]
Implemented.

**Comment by jen-tolentino** [comment]
That's perfect, thank you!
