### ISSUE TITLE
Removing Election Name from Tool

### ISSUE THREAD

**Issue by jen-tolentino** [votinginfoproject/vip-embeddable-tool#158]
We'd like to remove the Election Name, which is displayed above the election date. We'd prefer to simply display the date of the upcoming election.

For example, in the image below, rather than "US General Election 2014," it would simply be Tuesday, November 4, 2014.

![image](https://cloud.githubusercontent.com/assets/5825049/9451685/14db7bee-4a7e-11e5-8a62-ff7a56b6ef39.png)

**Comment by yulheecho** [comment]
Hi Jen,

Our concern on this item is that when there are multiple elections, the user will see a "+" on that section header and need to choose from a list of elections. Without the Election Name, this would be confusing. 

Let us know what you think about keeping it. 

Yulhee
<img width="813" alt="screen shot 2015-08-25 at 3 43 59 pm" src="https://cloud.githubusercontent.com/assets/8332232/9477441/4716199e-4b40-11e5-88d3-8b30f912ff42.png">

**Comment by jen-tolentino** [comment]
Hey Yulhee,

From research we've done around how voters look for election information, we're confident that just showing a list of dates would be sufficient. We don't have enough control over the election names to ensure they would necessarily be helpful, but we do know that most voters would be just as well off knowing the date of an election, rather than whether its a special/general/primary, etc.

Let me know if that makes sense or if there are any other concerns!

Jen

**Comment by alexkonrad** [comment]
Updated.
