### ISSUE TITLE
Adding Notes to Format select for customizer

### ISSUE THREAD

**Issue by jen-tolentino** [votinginfoproject/vip-embeddable-tool#159]
We've been demonstrating this customizer tool (lots of high praise!) but one area of confusion for many users has been the Format selection. Can you please add a Note, similar to what was included for the Alerts section, that clarifies the various options?

Let me know if you need more information on this request. Thank you!

**Comment by mickeysanchez** [comment]
Hi Jen, 

Two options I can think of for this:

1. A note that is always there that says something like, "Choose from a variety of fixed sizes, or a responsive tool that will stretch to fill its parent container."

2. A note next to each dropdown option:
  - 640x480 - Fixed height and width
  - 320x240 - Fixed height and width
  - Responsive - Stretches to fill parent container

Or both. Let me know

**Comment by kthale** [comment]
Hi @mickeysanchez,

An FYI that Jen left and I will be taking over management of the VIT.

I prefer the second option, with the note next to each drop down option. 

Thanks!

**Comment by mickeysanchez** [comment]
Sounds good and nice to meet you : ) 

Change is now pushed to production.
