### ISSUE TITLE
Urgent - Images not loading in embeddable tool

### ISSUE THREAD

**Issue by MariaDemocracyWorks** [votinginfoproject/vip-embeddable-tool#161]
The images in the Voting Information tool are currently not loading. We're seeing this behavior on different computers/networks, and it's happening on both the staging instance of the tool and the live one at votinginfoproject.org. Since there are several states using the tool embedded on their own websites for upcoming elections, we need this to be fixed as soon as possible.

Thank you!

![screen shot 2015-09-07 at 10 08 39 am](https://cloud.githubusercontent.com/assets/7061871/9718351/f4f9e92a-5548-11e5-9e77-312b7fa54455.png)
![screen shot 2015-09-07 at 10 09 01 am](https://cloud.githubusercontent.com/assets/7061871/9718352/f6a03cca-5548-11e5-9950-8bb6bb1b109d.png)

**Comment by jungshadow** [comment]
@alexkonrad Looks like the `src` attributes that are being written to the page are relative rather than absolute:

```html
 <div class="address-info box">
  <img src="images/voting-information-project.png" id="user-image" style="max-width: 85%;">
  <h1 class="title">Voting Information Project</h1>
  <h2 class="subtitle"></h2>
  ...
</div>
```

**Comment by alexkonrad** [comment]
Updated on vip-voter-information-tool-staging, vip-voter-information-tool, and vip-embeddable-tool.

**Comment by jungshadow** [comment]
@alexkonrad Works for me on VIP.org. @MariaDemocracyWorks Can you confirm on one of the external sites and close if all looks good to you?

**Comment by MariaDemocracyWorks** [comment]
This looks good now. Thanks, @alexkonrad!
