### ISSUE TITLE
Kansas State Seal Stretching in Embed

### ISSUE THREAD

**Issue by kthale** [votinginfoproject/vip-embeddable-tool#162]
The Kansas state seal is stretching horizontally in an embed. This happened previously and was fixed, but seems to be an issue again. Website here: http://www.knssradio.com/pages/21782394.php?polling-location

![knss](https://cloud.githubusercontent.com/assets/3733857/9857642/af0c1612-5ae9-11e5-83c0-cb66e2fcb2c4.png)

**Comment by alexkonrad** [comment]
Updated.
