### ISSUE TITLE
Edit language in tool to remove mention of "voter ID" and "what you need to bring to the polls"

### ISSUE THREAD

**Issue by kthale** [votinginfoproject/vip-embeddable-tool#163]
Because we have removed Voter ID resources from the tool completely, we need to edit some of the language in the tool.

1) Landing page--please remove "what you need to bring to the polls" from: "Find out where to vote, what's on your ballot, what you need to bring to the polls, and more..."
2) Voter Resources header--please remove "Voter ID information" from following:  "Information on how to navigate the elections process, including deadlines, Voter ID information, and registration links."

Thank you.

**Comment by alexkonrad** [comment]
Updated.
