### ISSUE TITLE
Change "Elections" tab to read "Election Date"

### ISSUE THREAD

**Issue by kthale** [votinginfoproject/vip-embeddable-tool#164]
The election name no longer displays in the tab, and now instead there's only the date. It makes sense to reflect this and change the tab header to read "Election Date."

Because we are changing the functionality right now in the tool to handle closed primaries, please let me know if you think we should hold off on this.

**Comment by yulheecho** [comment]
Hi @kthale - We'll keep this on board for implementation right after we set the closed primary updates. This way we can make sure it makes sense with the final flow in all circumstances.

**Comment by kthale** [comment]
I think that makes perfect sense @yulheecho. Thanks so much.
