### ISSUE TITLE
Proper Case Primary_Party

### ISSUE THREAD

**Issue by MariaDemocracyWorks** [votinginfoproject/vip-embeddable-tool#165]
Even in cases where the data supplied by the API is lower cased, primary_party should always be proper cased.

![primary_party_issue](https://cloud.githubusercontent.com/assets/7061871/10290024/ec5653d6-6b5e-11e5-8b5c-a0854a7b23a3.jpg)

@kthale

**Comment by alexkonrad** [comment]
Can I have an EID for this example? Thanks!

**Comment by MariaDemocracyWorks** [comment]
This is 4102.

**Comment by alexkonrad** [comment]
@MariaDemocracyWorks Thank you! This is fixed.
