### ISSUE TITLE
Footer language is justified to the wrong side in embed (running off tool)

### ISSUE THREAD

**Issue by kthale** [votinginfoproject/vip-embeddable-tool#166]
The footer language is justified to the right (instead of correct left) and running off the actual tool for the embed on the following page: http://www.davidvitter.com/find_your_polling_location 

![latool](https://cloud.githubusercontent.com/assets/3733857/10464705/2ae8c06a-71b9-11e5-8eb6-937696beb624.png)

**Comment by kthale** [comment]
@alexkonrad can you address this today or let me know the timeline for fixing this? It's embedded on a candidate's site for the upcoming Louisiana election. Thanks!

**Comment by alexkonrad** [comment]
Hi @kthale, I updated it and the changes have propagated so you should see it corrected on this live site now. It looks like the tool is being centered on that page using a deprecated HTML tag. I added an extra reset for that.

**Comment by kthale** [comment]
@alexkonrad it looks great. Thanks so much for taking care of this quickly! Much appreciated.
