### ISSUE TITLE
All locations showing the same name and address

### ISSUE THREAD

**Issue by acohen84** [votinginfoproject/vip-embeddable-tool#168]
@alexkonrad moving this to its own thread because I am now not the only person to experience it.  All locations in a county are showing the same name, address, and operating hours.  Someone from the SOS office in Colorado had the same experience with 6500 E Bethany Pl Denver CO 80224, though I am not experiencing the issue with that address.

**Comment by yulheecho** [comment]
Thanks @acohen84 we are looking into this, as well as the other location/proximity results that are popping up. Will have some more thoughts for you soon.
