### ISSUE TITLE
URGENT: Fixes to Legend, Matching seem to have Broken

### ISSUE THREAD

**Issue by MariaBianchi** [votinginfoproject/vip-embeddable-tool#171]
@acohen84 @alexkonrad @yulheecho 
On Saturday morning, after I cleaned the Colorado data, things looked good.
![screen shot 2015-10-31 at 10 31 31 am](https://cloud.githubusercontent.com/assets/7061871/10886608/cf91cc3c-8150-11e5-80ef-07c5defef07a.png)

The legend was not overlapping, and making sure the addresses matched had cleaned up the overlap problem significantly.

This morning, something seems to have changed. The legend is overlapping again, and the markers for Early Vote Sites and Drop-off sites are covering each other, even though the addresses seem to match.

![screen shot 2015-11-02 at 11 01 27 am](https://cloud.githubusercontent.com/assets/7061871/10886729/84142db2-8151-11e5-8e22-01c3cc7f0ce7.png)
![screen shot 2015-11-02 at 11 00 52 am](https://cloud.githubusercontent.com/assets/7061871/10886728/84135bc6-8151-11e5-9375-e2a336c94a41.png)

Any help would be very much appreciated.

**Comment by alexkonrad** [comment]
@MariaDemocracyWorks that looks different from what I saw on Saturday as well. Has the data changed at all? I haven't made any updates this weekend. I can add the formatting update (it looked like it wasn't necessary when I checked on Saturday), but if this is the final state of the data then I'll need to add that change.

**Comment by MariaDemocracyWorks** [comment]
It shouldn't have have changed at all over the weekend, and even looking at what's appearing in the tool now, the address data seems to be the same, just no longer displaying correctly.  

I'm just not sure what's happening. When you so formatting update, what do you mean?

**Comment by alexkonrad** [comment]
@MariaDemocracyWorks by formatting I meant the location legend pin

**Comment by MariaDemocracyWorks** [comment]
@alexkonrad 
Ah - I see.  In places where the green markers show up, the location legend looks fine. 

I have no idea what happened here, and as long as the tool is still matching on just the address lines, I'm not sure why those sites aren't being recognized as the same.

I re-uploaded the data from late Friday night just in case, but I have no real reason to believe that will fix anything, since the address data I'm seeing in the tool looks like it matches what's in the cleaned file. 

Has anything changed in the way addresses are matched? Or can you tell what's keeping that Christ Community Church result from matching?

**Comment by MariaDemocracyWorks** [comment]
@alexkonrad  Okay, the clean data has definitely been refreshed, and the problem persists. 

I'm not sure how to fix this.  How do I make the address lines match more than they already do?

Denver,Christ Community Church,8085 E Hampden Ave,,,Denver,CO,80231,,Drop off,2015-10-26,2015-11-03,10/26-11/2 Mon-Fri 10-6; 10/31 Sat 10am-2pm; 11/3 Tue 7am-7pm,22207890

Denver VSPC,Christ Community Church ,8085 E Hampden Ave,,,Denver,CO,80231,,VSPC,2015-10-26,2015-11-02,10/26-11/2 Mon-Fri 10-6; 10/31 Sat 10am-2pm,22208023

**Comment by MariaDemocracyWorks** [comment]
@acohen84 @alexkonrad @yulheecho 

This is fairly urgent, since it's holding up publication of Colorado's data. Also, if I need to make changes to the data, I need to get them in by 1:00 ET, or I have to wait until 3:00.

**Comment by alexkonrad** [comment]
Looking into this now!

**Comment by alexkonrad** [comment]
@MariaDemocracyWorks I believe this is a bug related to removing expired early vote sites. I'm working on a patch right now.

**Comment by MariaDemocracyWorks** [comment]
Thank you!

Maria Bianchi
Project Manager | Voting Information Project
Democracy Works
maria@*democracy.works* <maria@democracy.works>
(o): 718-923-1400 ext. 3000 | (c): 716-908-5617

**Comment by alexkonrad** [comment]
Let me know if you're able to take a look here and verify with the Bethany Pl address: http://s3.amazonaws.com/vip-voter-information-tool-staging/configurable.html

**Comment by MariaDemocracyWorks** [comment]
Hmmm
I get this:

![screen shot 2015-11-02 at 1 06 57 pm](https://cloud.githubusercontent.com/assets/7061871/10889886/a7f42e1a-8162-11e5-9da3-48abd83d791f.png)

Which is missing all indicatiors

**Comment by alexkonrad** [comment]
@MariaDemocracyWorks That's for 2014. You can enable a different election in the input field below. Otherwise I can push a sample tool set to 4147

**Comment by MariaDemocracyWorks** [comment]
You're correct. With the right EID, there are still no indicators, and it looks like the church is still coded as only a drop-off

![screen shot 2015-11-02 at 1 10 54 pm](https://cloud.githubusercontent.com/assets/7061871/10889996/3dccd1bc-8163-11e5-9d9c-3ad41fa06715.png)

**Comment by alexkonrad** [comment]
@MariaDemocracyWorks what browser is this?

**Comment by MariaDemocracyWorks** [comment]
Chrome.

**Comment by alexkonrad** [comment]
I'm seeing something different for that address. I'm using EID 4147 with staging data checked, but not official only. Am I using the correct EID and options?

**Comment by MariaDemocracyWorks** [comment]
Yes. And when I try it in Safari, the indicators show up, but it looks exactly like it does in the production version of the tool, with drop-offs overlaying EV sites, except that the legend is cleaner.

![screen shot 2015-11-02 at 1 15 50 pm](https://cloud.githubusercontent.com/assets/7061871/10890092/067856c2-8164-11e5-889e-b19c302c7e10.png)

**Comment by alexkonrad** [comment]
Ok. It's removing the early vote sites because today is the end date. I'm assuming they should actually be removed tomorrow, right?

**Comment by MariaDemocracyWorks** [comment]
@alexkonrad 
Are you sure that's what's happening? Because I'm still seeing both Early Vote and Drop-offs displayed. (If you click the Early Vote indicator in the legend it surfaces it.) It's just that instead of being matched as a combined EV + Drop off, they're being stacked on top of each other.

**Comment by alexkonrad** [comment]
@MariaDemocracyWorks It's only displaying one EV location (Montclair) because that one has no end date

**Comment by MariaDemocracyWorks** [comment]
I see that now. That isn't ideal, since EV continues til 8ET/6CT tonight. More of a problem is that now no Election Day polling locations are displaying.

![screen shot 2015-11-02 at 1 29 35 pm](https://cloud.githubusercontent.com/assets/7061871/10890401/ca0cc158-8165-11e5-86bb-969299d0c64f.png)

**Comment by MariaDemocracyWorks** [comment]
@alexkonrad Is something in the tool attempting to handle expiring EV sites? My understanding was that the civic API took care of that, where possible.

**Comment by alexkonrad** [comment]
@MariaDemocracyWorks Yes, that was a feature we had for v1. I can either remove it or adjust the comparison to check for the day after.

**Comment by alexkonrad** [comment]
I'd prefer to remove it if the API takes care of that.

**Comment by MariaDemocracyWorks** [comment]
@alexkonrad @acohen84 Does it seem like adjusting the comparison to the day after would allow the sites to match?

**Comment by MariaDemocracyWorks** [comment]
@alexkonrad @acohen84 Or removing it for that matter? In the data up on staging in the production tool, it doesn't seem like expired EV sites is the problem, in that they still show up, just are covered.

The missing Election Day polling locations in the staging tool also seem concerning.

**Comment by alexkonrad** [comment]
@MariaDemocracyWorks I'm not sure why you're not seeing the markers but I would imagine it has something to do with the setup of the staging environment, rather than something about the tool.

**Comment by MariaDemocracyWorks** [comment]
I'm seeing the same thing on the production version.

**Comment by alexkonrad** [comment]
I updated the staging to remove the expiry check. Take a look: http://s3.amazonaws.com/vip-voter-information-tool-staging/configurable.html

As for the Chrome issue, does this happen in an incognito window too? What version of Chrome are you using? If you could also open up the console window (Cmd+Opt+i) and send me any error messages you see that would be helpful.

**Comment by MariaDemocracyWorks** [comment]
I figured out the Chrome thing, was specific to my machine. 

This looks better, except now some of the drop offs are missing. That Christ Community Church location is a drop-off and an early vote site as well as a polling location.

![screen shot 2015-11-02 at 1 59 14 pm](https://cloud.githubusercontent.com/assets/7061871/10891112/10f07b92-816a-11e5-9fa4-0676bb6fabda.png)

**Comment by MariaDemocracyWorks** [comment]
@alexkonrad  Nevermind. I see what I did there.

**Comment by MariaDemocracyWorks** [comment]
@alexkonrad @acohen84 This looks good. The polling locations seem to be getting double counted, which is weird, but this is much better!

![screen shot 2015-11-02 at 2 06 41 pm](https://cloud.githubusercontent.com/assets/7061871/10891289/05b03cd0-816b-11e5-8e5b-5d8c24700806.png)

**Comment by alexkonrad** [comment]
@MariaDemocracyWorks I see that double counting too. Let me see if I can address that.

**Comment by MariaDemocracyWorks** [comment]
@alexkonrad Could we get this change live, even if the double-counting persists?

I'd love to be able to take this to the state ASAP.

**Comment by alexkonrad** [comment]
@MariaDemocracyWorks done. It will take a bit for tool.votinginfo... to update because I have to invalidate the CloudFront cacheing. I'll update when it's finished.

**Comment by alexkonrad** [comment]
@MariaDemocracyWorks updated.

**Comment by alexkonrad** [comment]
Addressing a possible fix to this issue in #179
