### ISSUE TITLE
Add new fields to customizer

### ISSUE THREAD

**Issue by alexkonrad** [votinginfoproject/vip-embeddable-tool#172]
The ability to customize the labels so that a state could customize the text to be more appropriate for their voting situation.  Two examples: in an all-mail state, we’d want the option to change it to say “Dropboxes” instead of “Polling Location;” or, a state might want to change “Absentee Voting Information” to “Mail Ballot Information.”

@yulheecho can you confirm which fields will need to be customized?

**Comment by yulheecho** [comment]
Based on my understanding from discussions with Amy, it should be:
* Left Sidebar/Navigation > Polling Location
* Map Detail > Polling Location
* Voter Resources > State Elections Office
* Voter Resources > Election Information
* Voter Resources > Registration Confirmation
* Voter Resources > Absentee Voting Information
* Voter Resources > Voting Location Finder
* Voter Resources > Ballot Information

@acohen84 can you confirm this is an exhaustive list? If not, let us know what the final editable fields should be. 

Thanks!
Yulhee
![image002](https://cloud.githubusercontent.com/assets/8332232/12129182/ef96fe2e-b3cf-11e5-9b1b-320fb8d3e529.png)
![image003](https://cloud.githubusercontent.com/assets/8332232/12129183/ef9baa5a-b3cf-11e5-9299-40752ffdb47e.png)

**Comment by acohen84** [comment]
@alexkonrad @yulheecho Yes, that looks right.  Thanks!

**Comment by yulheecho** [comment]
Hi @acohen84 Here's a solution that @mickeysanchez came up with. Let us know if this is sufficient and we'll finalize this. 
<img width="1340" alt="collapsed" src="https://cloud.githubusercontent.com/assets/8332232/12174908/5580cd60-b52d-11e5-939e-527255cc174f.png">
<img width="1257" alt="expanded" src="https://cloud.githubusercontent.com/assets/8332232/12174907/557e0ea4-b52d-11e5-96f4-49a62bc3e7d8.png">

**Comment by ZachMarko** [comment]
This is exactly what I was imagining, but I’d like to shorten the second line of text to: “The following text is not shown in the customizer preview, but will appear in your embedded tool.”  Important follow up question: will there be spell check?

Thank you for translating my garbled idea into reality!

**Comment by yulheecho** [comment]
hi @ZachMarko @acohen84 Sounds great! Regarding the spell check, yes, we should be able to support this feature, given we still have some hours available from what we allocated for this feature, and that @mickeysanchez was able to find a javascript library that would make this possible. We'll keep you posted with our progress.

Thanks!

**Comment by acohen84** [comment]
Thanks @yulheecho!  I worry that someone changing the text would inadvertently spell something wrong and would like to nip that in the bud if we can.

**Comment by acohen84** [comment]
Hi all.  Just wanted to check in on this.  Thanks!

**Comment by mickeysanchez** [comment]
@acohen84 

I've pushed up this addition on staging for you to check out: http://s3.amazonaws.com/vip-voter-information-tool-staging/cms/index.html

Spell check is working, however there is one issue:

On Chrome, the final word in a box does not spellcheck unless you press spacebar after entering it. 

The spellcheck we are using is a built in browser feature and works differently across all browsers. We are looking for a workaround for this, but it is unlikely that we can fix the issue unless we take another approach to spellchecking entirely (like using a javascript library). We will keep searching for a workaround for now, but let us know how you'd like us to proceed.

**Comment by acohen84** [comment]
Sorry for my slow response - this looks great and is exactly what I was envisioning.  I'm comfortable with deploying as is, and continuing to look for a workaround.  Sound good?
