### ISSUE TITLE
Display closest location of any type first

### ISSUE THREAD

**Issue by alexkonrad** [votinginfoproject/vip-embeddable-tool#173]
This functionality can be previewed on the [staging tool](http://s3.amazonaws.com/vip-voter-information-tool-staging/configurable.html) by setting EID to 4147 and entering a Colorado address (e.g. "18 s dahlia st denver co"). I'm still working on testing different scenarios of location types but the core functionality is there.

**Comment by acohen84** [comment]
Approved, sorry, I didn't see this notification.
