### ISSUE TITLE
Increase the speed of displaying dropoff locations

### ISSUE THREAD

**Issue by alexkonrad** [votinginfoproject/vip-embeddable-tool#174]
This functionality can be previewed on the [staging tool](http://s3.amazonaws.com/vip-voter-information-tool-staging/configurable.html?polling-location). For locations with several dozen locations, the loading speed should be improved, particularly for the first dozen or so closest locations. We can continue to tweak this to see what sort of improvements we can get before deciding whether to implement the back-end solution as well.

**Comment by acohen84** [comment]
I'm not seeing this with the test addresses I'm trying - with 4283 Hooker St, Denver, CO the map doesn't load at all, and with an address in Fairplay, only one VSPC popped up.  What test addresses are you using?

**Comment by alexkonrad** [comment]
I'm using the configurable tool with EID 4147 and address "18 s dahlia st denver co." This was just meant to be a preview though to give you a feel for the way dropboxes are loading, so I'm going to push the finished product up sometime tomorrow.

**Comment by alexkonrad** [comment]
Amy,

I pushed some new updates for this to the staging tool:

1. Locations returned by the Civic Information API are pre-sorted by zip code before we make the geocoding requests to the Google Maps API to get the exact coordinates of the locations. Previously, although polling locations were sorted by distance, as well as early vote sites, drop-off locations, there was no way for us to know whether a polling location was closer to the entered location than say a drop-off location or early vote site before making a geocoding request. Now, because we pre-sort by zip codes, if a drop-off location is closer to the registered address than a polling location the drop-off location will be prioritized for geocoding. The effect of this is that in a state like CO the priority geocodes will be the closest locations of any type, not just the closest polling locations.

2. We increase the rate of geocoding requests after failures from the Google Maps API, resulting in a modest speed increase for the total geocoding task. The Google Maps API employs client-side rate limiting, so after obtaining coordinates for ~10 locations the API starts blocking these requests and will only fulfill them after a wait of about 1 second. After this point it will usually only allow geocoding about 1 at a time with a similar gap in between. This is only really a problem in states with many drop-off locations like CO. We changed the app to retry the requests more aggressively. From some tests I ran with CO addresses it looked like about a 15% speed-up, which is not game-changing but still helpful.

3. We set the map to focus initially only on the closest couple of locations as well as the registered address. Previously we drew the map bounds around all the available locations, which was helpful in other states but for a state like CO was too zoomed out and would draw attention to the additional loading locations. Because we're now loading all types of locations in order of proximity, the last locations to be loaded will in general be the locations furthest away from the registered address. This gives us time to load the last remaining locations before the user chooses to pan around and zoom out from the initially loaded location.

You can view these changes from the link I gave above. I usually use 4147 for testing of these types of locations -- there is an input field at the bottom of the page where you can select the election ID. Please let me know if you're having trouble seeing these changes!

Best,
Alex

**Comment by acohen84** [comment]
Thanks Alex, I'm definitely noticing increases in speed (hooray!), but I'm also noticing that the white pop-up box won't close, which makes it hard to maneuver around the interface  Can you fix that?

**Comment by alexkonrad** [comment]
@acohen84 this is updated.

**Comment by acohen84** [comment]
Approved, sorry for the delay!
