### ISSUE TITLE
Remove zipcode autofill

### ISSUE THREAD

**Issue by alexkonrad** [votinginfoproject/vip-embeddable-tool#176]
@acohen84 would you be able to provide me with an example of those problematic New Jersey addresses from different towns with the same name? We're experimenting with some different options right now and I'm trying to isolate where exactly the autocomplete is making the wrong choice.

**Comment by acohen84** [comment]
@alexkonrad Sure.  24 1st street, Franklin, NJ.  There's one in Gloucester County, NJ and one in Somerset County, NJ.  I can also forward you an email exchange on this if it's helpful.

**Comment by alexkonrad** [comment]
@acohen84 Yes, the email exchange might be helpful! Thanks.

**Comment by alexkonrad** [comment]
Note: when we first implemented address suggestions, the Pew team had a strong desire to prefer the user input to the Google Maps suggestions if the user had not explicitly selected one of the autocomplete options. If you enter an address and click submit without choosing one of the suggestions, the tool will take the exact address you entered and submit it to the Civic Information API. This is what happens in the example that the election officials sent over. In order to implement a "fix" for this, we would have to manipulate the user's entered information and so would violate that desire to prefer the user's input over any suggestions if they didn't choose one.

**Comment by acohen84** [comment]
Okay.  My understanding of the example I sent, though, was that it was the exact same street address in two different counties - you're saying they're slightly different street addresses, right?  If they were exactly the same (ie - 15 Main Street, Whotown; 15 Main Street Whotownville), can you confirm that the tool won't default to one, but will require the user to either finish typing or select an address?

**Comment by alexkonrad** [comment]
The Civic Information API is responsible for deciding how to interpret the user's entered address. Here's an example using their sample tool. Say you enter in `24 1st st franklin nj`:
![image](https://cloud.githubusercontent.com/assets/4000470/13674221/a9f44e90-e6aa-11e5-849a-eaf2e7c46c52.png)
It interprets `24 1st st franklin nj` as being the 08873 address:
![image](https://cloud.githubusercontent.com/assets/4000470/13674283/e78ae336-e6aa-11e5-8020-61eedeee4492.png)
But if you enter `24 1st st franklin nj 08322`:
![image](https://cloud.githubusercontent.com/assets/4000470/13674338/206d2e02-e6ab-11e5-98a7-d5895394c759.png)
It will interpret it as being the other (08322) address:
![image](https://cloud.githubusercontent.com/assets/4000470/13674361/3210c0a6-e6ab-11e5-8a94-deb8cd86e2a0.png)
So in this case when the less specific address is entered `24 1st st franklin nj`, the API itself makes a judgement about what address is being entered.

**Comment by acohen84** [comment]
Ah, okay.  Thanks for digging into this.  I think we can call this one closed.

**Comment by alexkonrad** [comment]
@acohen84 to answer your question: assuming that there are two addresses that are exactly the same, the Civic Information API will make a judgment about which address was entered and return the information for that address.
