### ISSUE TITLE
Adding Event to GCal leads to strange "Where" line

### ISSUE THREAD

**Issue by MariaBianchi** [votinginfoproject/vip-embeddable-tool#177]
When I click the calendar icon on the tool to add an event to my Google Calendar, an event is successfully created, but the "where" line is pretty strange and not human readable. Is that intentional?

![screen shot 2016-02-08 at 11 32 26 am](https://cloud.githubusercontent.com/assets/7061871/12891948/f9f72f72-ce57-11e5-9902-1f53fff47df1.png)

@acohen84

**Comment by alexkonrad** [comment]
This is a bug in the data transfer to the calendar. I'll post an update to this today.

**Comment by alexkonrad** [comment]
Fixed.
