### ISSUE TITLE
Tool moving around on page

### ISSUE THREAD

**Issue by acohen84** [votinginfoproject/vip-embeddable-tool#178]
The tool on the Rock the Vote page will not stay in one place.  See screenshot below - the first one is displaying correctly, and the second one is after scrolling.  I'm not sure if this is something with their instance or with our tool, but wanted to flag it.

![rtv1](https://cloud.githubusercontent.com/assets/11788886/12901640/ba0082dc-ce8a-11e5-8d38-8dce1e9c8fa7.jpg)
![rtv2](https://cloud.githubusercontent.com/assets/11788886/12901641/ba0615b2-ce8a-11e5-8373-260c6a91b518.jpg)

@alexkonrad

**Comment by alexkonrad** [comment]
@acohen84 It looks like the site is applying one of its own styles related to stacking to the tool. I'll change the tool to remove the mix-up.

**Comment by acohen84** [comment]
@alexkonrad Thanks!  Will RTV need to update their tool, or should the fix happen automatically?

**Comment by alexkonrad** [comment]
It will be automatic. I'll update when it's live.

**Comment by alexkonrad** [comment]
Fixed.
