### ISSUE TITLE
Odd display on embed

### ISSUE THREAD

**Issue by acohen84** [votinginfoproject/vip-embeddable-tool#180]
The EAC has embedded our lookup tool (http://www.eac.gov/voter_resources/contact_your_state.aspx?polling-location), and it's displaying very strangely.  The search box is too wide, and then all of the information returned has weird justification.  In addition, if you hit "enter" when searching for an address, the tool opens and then closes.  Try 1500 Fairbanks Ave, Norfolk, VA.

All of these could be issues with that particular embed, but I'd like to be able to give them specific feedback.

@alexkonrad

**Comment by alexkonrad** [comment]
@acohen84 The width issue has to do with the container it's embedded in. I can set a restriction on the width and notify you when that's updated.

Looking into that open/close issue, I've never seen that before. I think there might be an event handler on the containing page causing a conflict in behavior.

**Comment by acohen84** [comment]
Thinking through this a little bit, I think the open close issue is related to their embed - the state of Connecticut has something similar and I believe it's because somehow the embed is attached to a form on their website.  

Once you let me know about the first part, I'll reach out to one of the Commissioners and let him know about the issues.  They've been moving the tool around a little bit on their page, so this may not be the final home, either.

**Comment by alexkonrad** [comment]
That's similar to what I'm thinking too. There's an event handler on the page listening for certain keys like the enter key because it's a search page, so when you enter an address in the tool the page is interpreting it as a search query too, and navigating you to the their search results page. I've tried a couple different things so far but it's always a little tricky accounting for different possibilities in an embed.

**Comment by alexkonrad** [comment]
@acohen84 The appearance of the tool on this page is now fixed: I added a width constraint to compensate for the type of container and made sure to "clean out" the tool container of any extra characters the website may automatically add in the process of embedding it. The autocomplete issue still remains. Please reopen if we should continue working for a solution on this.
