### ISSUE TITLE
Early Vote Site Name not displaying in the tool

### ISSUE THREAD

**Issue by MariaBianchi** [votinginfoproject/vip-embeddable-tool#181]
The Elections Director in Oklahoma called to ask why the name of Early Vote Sites aren't showing up in the tool, which they'd like to use alongside their own.

It looks like this is because the tool isn't displaying the "Name" field in Early Vote Location, only the "Address Location Name" field from address. We should be displaying both, if possible.

@acohen84

**Comment by alexkonrad** [comment]
That sounds correct. I believe we removed one version of the location names fields in a previous election cycle because of duplicates. I can add these back in.

**Comment by MariaBianchi** [comment]
Thanks, yes! That sounds familiar to me, so I think we probably did ask for that at one point, but we should probably handle duplicates in the data, since those fields can represent different things.

**Comment by acohen84** [comment]
In the event that you're waiting for me to weigh in here, I'm comfortable moving forward with this change.

**Comment by alexkonrad** [comment]
@MariaBianchi this is now updated on the live tool. I'm seeing the name being displayed for the early vote sites testing with these addresses:

- 10627 NE 38 ST SPENCER OK 73084
- 107 S LOUISVILLE AVE TULSA OK 74112
- 107 W SPRUCE AVE DUNCAN OK 73533
- 10705 NW 40 TER YUKON OK 73099
