### ISSUE TITLE
Change text from closed primary screen

### ISSUE THREAD

**Issue by acohen84** [votinginfoproject/vip-embeddable-tool#182]
Based on feedback from the states and the ever complicated way that elections are run, we need to change the text on the closed primary screen. 

Instead of: "This election is only open to registered members of the listed parties. Please select your party to continue." the text should now read "Select a party to continue."

Thanks!

@alexkonrad @mariabianchi

**Comment by MariaBianchi** [comment]
![image001](https://cloud.githubusercontent.com/assets/7061871/13297337/e1754966-daff-11e5-9e9f-463e026b347a.png)

**Comment by alexkonrad** [comment]
I should be able to have this updated before the end of the day. I'll keep you posted.

**Comment by MariaBianchi** [comment]
That's great news, Alex! Please let me know when it's live - I have a state waiting for this change to publish their data.

**Comment by alexkonrad** [comment]
Updated. I currently can't find any addresses with closed primaries to check but it's a straightforward copy change.

**Comment by MariaBianchi** [comment]
This looks perfect, thanks!
