### ISSUE TITLE
Ballot Data not Appearing

### ISSUE THREAD

**Issue by MariaBianchi** [votinginfoproject/vip-embeddable-tool#184]
For Delaware's Primary (EID 4197) ballot data isn't appearing once you click on the party selection options. 

For test address: 29701 COLONY DR DAGSBORO DE 19939

I see this as expected

![screen shot 2016-03-26 at 6 48 28 pm](https://cloud.githubusercontent.com/assets/7061871/14062812/5c422f10-f383-11e5-97ac-b6f348a31a1e.png)

but when I click on the Democratic or Republican Party options, I see this:

![screen shot 2016-03-26 at 6 49 28 pm](https://cloud.githubusercontent.com/assets/7061871/14062822/b7ba8a54-f383-11e5-9022-51af70130358.png)

I initially thought this was a data issue, but the data displays successfully in the old Google VIT, so I'm not sure what's causing it to break in the embeddable tool.

**Comment by alexkonrad** [comment]
@MariaBianchi thank you for the screenshots -- this is now fixed in the live tool.

**Comment by alexkonrad** [comment]
The tool wasn't selecting based on primary party name correctly.

**Comment by MariaBianchi** [comment]
Thank you so much for the quick fix. It looks great now!
