### ISSUE TITLE
Mobile display issues

### ISSUE THREAD

**Issue by acohen84** [votinginfoproject/vip-embeddable-tool#187]
@alexkonrad @itsjustdanger 

I received a report of a "weird" mobile display on an iPhone 5 - the entry field didn't fit vertically and the submit button wasn't visible on landscape.  I'm not able to replicate this on my 6, but can you look into it?

What I am seeing on my 6, though, is that when an address does return results, you can't scroll through the interface to get down to voter resources or ballot information, and the only way to do that isn't intuitive (clicking the +/-) sign.  Try 146 Donelson Street, Providence, RI on mobile to see what I mean.  Even if you can figure out your way around the information, it isn't clear how you return to the site you were visiting.  This is the case on both VIP's website embed and on other embeds of the tool.

Thanks!

**Comment by acohen84** [comment]
@itsjustdanger @alexkonrad @yulheecho Checking on this...

Thanks.

**Comment by yulheecho** [comment]
Hi @acohen84 - Sorry for the silence! We've been working on this and should have sent through confirmation of receipt. We're not seeing the issue on Dev but have some other work there that is not fully complete, so we're trying to isolate why there might be an issue on Staging and not Dev. @itsjustdanger will follow up soon with our findings and progress.

**Comment by acohen84** [comment]
Thanks!

**Comment by alexkonrad** [comment]
This is working now on the few iOS devices I've tested (5, 6). Please reopen if you see this issue on another one.

**Comment by acohen84** [comment]
So much better!  I'm still not able to intuitively get back to the webpage I was on though.

**Comment by alexkonrad** [comment]
@acohen84 When we originally designed this we discussed it and concluded using the browser's back button is the best way to get back to the webpage you were on. That should be working -- I agree it might not be the most intuitive solution.

Another option would be to include some kind of hovering exit button on mobile.

**Comment by acohen84** [comment]
Meant to respond to this, but THANKS!  I don't think it's a big enough deal right now to add an exit button, but I've confirmed that the tool is displaying better on mobile now.
