### ISSUE TITLE
"Use Current Location" Feature not working

### ISSUE THREAD

**Issue by MariaBianchi** [votinginfoproject/vip-embeddable-tool#188]
The state of Oregon pointed out that the "Use Current Location" feature for by mail elections doesn't seem to be working. 

It's offered as an option on the "Mail-in Voting State" pop up
![vip_stage](https://cloud.githubusercontent.com/assets/7061871/14767928/88b156f0-0a00-11e6-83b9-c1da9c65f9df.png)

but if selected, it fails to load:
![vip_stage2](https://cloud.githubusercontent.com/assets/7061871/14767935/b366ff58-0a00-11e6-9cab-6760335576af.png)

You can see this behavior with address: 290 Gardenia Dr N Salem, OR 97303

Oregon is hoping to embed the tool on their website, so it would be wonderful if we could get this fixed!

@acohen84

**Comment by alexkonrad** [comment]
Updated.
