### ISSUE TITLE
Customizer not working properly

### ISSUE THREAD

**Issue by acohen84** [votinginfoproject/vip-embeddable-tool#190]
@itsjustdanger @alexkonrad 

We heard from a state that when they use the customizer to change the labels (under advanced settings), the resulting code doesn't work.  I've pasted the code below.  According to their email, when they add the json object into the code, the first screen of the page comes up blank.  This is a little time sensitive.

Thanks!

<script type="text/javascript" src="https://tool.votinginfoproject.org/app.js"></script>
<div id="_vit"></div>
<script type="text/javascript">vit.load({
    modal: true,
    width: '640px',
    height: '480px',
    colors: {
      'header': '#229acd',
      'landscapeBackgroundHeader': '#228a9d'
    },
    language: 'en',
    json: {
      text: {
        headers: {
          pollingLocation: 'Drop-off Location'
        },
        resources: {
          electionAdministration: {
            stateElectionsOffice: 'State Elections Office'
          },
          moreResources: {
            electionInformationUrl: 'Election Information',
            registrationConfirmationUrl: 'Registration Confirmation',
            absenteeVotingInformationUrl: 'Absentee Voting Information',
            votingLocationFinderUrl: 'Voting Location Finder',
            ballotInformationUrl: 'Ballot Information'
          }
        }
      }
   }
});</script>

**Comment by acohen84** [comment]
"<script type="text/javascript" src="https://tool.votinginfoproject.org/app.js"></script>
<div id="_vit"></div>
<script type="text/javascript">vit.load({
    modal: true,
    width: '640px',
    height: '480px',
    colors: {
      'header': '#229acd',
      'landscapeBackgroundHeader': '#228a9d'
    },
    language: 'en',
    json: {
      text: {
        headers: {
          pollingLocation: 'Drop-off Location'
        },
        resources: {
          electionAdministration: {
            stateElectionsOffice: 'State Elections Office'
          },
          moreResources: {
            electionInformationUrl: 'Election Information',
            registrationConfirmationUrl: 'Registration Confirmation',
            absenteeVotingInformationUrl: 'Absentee Voting Information',
            votingLocationFinderUrl: 'Voting Location Finder',
            ballotInformationUrl: 'Ballot Information'
          }
        }
      }
   }
});</script>"

**Comment by acohen84** [comment]
Okay, it won't let me copy and paste the code, I'll email it to you.

**Comment by alexkonrad** [comment]
Thanks @acohen84. Looking into this now.

**Comment by alexkonrad** [comment]
Updated.
