### ISSUE TITLE
Default language tweaks

### ISSUE THREAD

**Issue by acohen84** [votinginfoproject/vip-embeddable-tool#191]
Can you change the default name of the "Polling Location" tab to "Voting Location" and "Polling Hours" to "Voting Hours"?  If this could be done today, that would be great.

@alexkonrad @itsjustdanger

**Comment by alexkonrad** [comment]
@acohen84 We can do that today--I'll let you know when it's updated.

**Comment by alexkonrad** [comment]
This is updated.

**Comment by acohen84** [comment]
@alexkonrad Washington State just pointed out that we missed one.  Can you change "polling location" in the map legend to "voting location"?

**Comment by alexkonrad** [comment]
Updated.
