### ISSUE TITLE
NC Ballot Data Not Working

### ISSUE THREAD

**Issue by MariaBianchi** [votinginfoproject/vip-embeddable-tool#192]
The State of North Carolina alerted us to an issue where their ballot data isn't showing up in the VIT properly. Since the data is live, and they've embedded the tool on their website, this is fairly urgent.

For sample address: 9 GROVE GARDEN AVE CANDLER, NC 28715

the API should be returning 2 contests, a Democratic Congressional Primary and a State Supreme Court race:

 "contests": [
  {
   "type": "PRIMARY",
   "primaryParty": "DEM",
   "office": "US HOUSE OF REPRESENTATIVES DISTRICT 11",
   "district": {
    "name": "US HOUSE OF REPRESENTATIVES DISTRICT 11"
   },
   "ballotPlacement": "3",
   "candidates": [
    {
     "name": "Tom Hill",
     "party": "DEM",
     "phone": "828-693-5727"
    },
    {
     "name": "Rick Bryson",
     "party": "DEM",
     "phone": "828-488-1393"
    }
   ],
   "sources": [
    {
     "name": "Voting Information Project",
     "official": true
    }
   ]
  },
  {
   "type": "PRIMARY",
   "office": "NC SUPREME COURT ASSOCIATE JUSTICE",
   "district": {
    "name": "NC SUPREME COURT ASSOCIATE JUSTICE",
    "scope": "statewide"
   },
   "ballotPlacement": "39",
   "candidates": [
    {
     "name": "Michael R. (Mike) Morgan"
    },
    {
     "name": "Sabra Jean Faires",
     "phone": "919-481-2785"
    },
    {
     "name": "Robert H. (Bob) Edmunds"
    },
    {
     "name": "Daniel Robertson"
    }

However, when I try the address in the tool, I get:

![screen shot 2016-05-16 at 10 52 29 am](https://cloud.githubusercontent.com/assets/7061871/15293098/514e81f0-1b54-11e6-83b9-9de78bf56452.png)

But can't go any further - clicking on the Democratic button produces no result.

Do you know what's triggering this behavior?

**Comment by alexkonrad** [comment]
Hi Maria, confirming receipt. We're looking into this now.

Alex Konrad

**Comment by alexkonrad** [comment]
Fixed. There was an issue with the calendar code parsing the dates for these contests.

**Comment by MariaBianchi** [comment]
Thanks! That seems to have fixed it!

Maria Bianchi
Project Manager | Voting Information Project
Democracy Works
maria@*democracy.works* <maria@democracy.works>
(o): 718-923-1400 ext. 3000 | (c): 716-908-5617
