### ISSUE TITLE
Current Location Functionality by County

### ISSUE THREAD

**Issue by acohen84** [votinginfoproject/vip-embeddable-tool#193]
Is it possible to turn on the "current location" functionality for an individual county in a state that does not have droboxes for the entire state?  Los Angeles County has implemented dropboxes for their upcoming election on June 7, but dropboxes are not in use statewide.
@itsjustdanger @alexkonrad

**Comment by itsjustdanger** [comment]
Hey @acohen84, confirming receipt. I'm looking into this, but it may not be possible to implement. It looks like the civic information API only returns nearby drop box locations based on the entered address and not all the drop box locations for the state. This means it will be difficult, if not impossible, to programmatically determine whether there are drop boxes for an entire state based only on a given address. 

It may be possible to implement this if we hardcoded a running list of states with drop boxes that are not in use state-wide, and then compared this to whether the API returned any drop off locations in the local search. However, this may be a bit burdensome to compile and constantly update the tool based on, what I image, is a moving target in terms of data.

I'll continue to look into this and let you know what I discover.

**Comment by itsjustdanger** [comment]
One way we could implement this for the CA election is to simply hard code the counties where we want the 'current location' functionality to appear. It may be easier to just implement this statewide and exclude counties that do include drop boxes. Would this be sufficient? @acohen84

**Comment by acohen84** [comment]
Thanks @itsjustdanger.  Ultimately, the county doesn't want to display the dropboxes this way for the June election, but it's good to know that it's doable because we'll revisit for November.
