### ISSUE TITLE
Current Location Functionality

### ISSUE THREAD

**Issue by acohen84** [votinginfoproject/vip-embeddable-tool#194]
We received a report from Oregon that the current location function did not work at all during the primary.  They only let us know on Tuesday, so we don't have live data for a dropbox election.
@itsjustdanger @alexkonrad

**Comment by alexkonrad** [comment]
•Confirming receipt. We'll look into this now.

**Comment by acohen84** [comment]
@alexkonrad Just realized I never heard back on this - can you update?

**Comment by alexkonrad** [comment]
We've updated this code but need to do a little more testing before we move it to production. I'll let you know early next week when we're ready!

**Comment by acohen84** [comment]
Hi @alexkonrad, just checking in.  We have a VBM election next month.

**Comment by alexkonrad** [comment]
Hi Amy,

We will be able to push the code for this today. The feature is set, but
Chrome has a new security policy surrounding geolocation functionality so
I'm looking to see if we need to add extra error messaging.

Alex Konrad

**Comment by alexkonrad** [comment]
This should be working correctly now. Unfortunately you can't test the current location functionality unless you are in the state (you will just see the out-of-state message)--let me know if you'd like me to add a version of the app to staging without this check for more testing.

On some browsers like Chrome > 50 current location functionality will not work on insecure HTTP origins. In this case the registered address is used instead.
