### ISSUE TITLE
Remove the word "Registered"

### ISSUE THREAD

**Issue by acohen84** [votinginfoproject/vip-embeddable-tool#195]
Can you remove the word "Registered" from the field above the user address in the attached?  This should be super quick and we'd love to have this done today if we can!

Thanks

![capture 6 7](https://cloud.githubusercontent.com/assets/11788886/15864894/bcf77476-2ca6-11e6-9ec2-08417ba42e03.JPG)

@alexkonrad @itsjustdanger

**Comment by alexkonrad** [comment]
Will do!

Alex Konrad
