### ISSUE TITLE
Issue with WordPress embed

### ISSUE THREAD

**Issue by acohen84** [votinginfoproject/vip-embeddable-tool#196]
We're seeing an issue with an embed on a California-based WordPress site - either the result is the below or the map won't display at all.  I know we've had this issue in the past, but I don't know how we resolved it.  Is this something you can handle, or does WordPress need to do something?  This is for today's election so it would be great to get this resolved quickly.

![screen shot 2016-06-07 at 12 11 30 pm](https://cloud.githubusercontent.com/assets/11788886/15872899/d55882d0-2cc9-11e6-982a-7cf086ab8c66.png)

**Comment by alexkonrad** [comment]
We were not able to fix this due to an issue with Google Maps API script loading conflicting with the embedding page's MooTools Javascript library.
