### ISSUE TITLE
Urgent - Maps API quota warning

### ISSUE THREAD

**Issue by MariaBianchi** [votinginfoproject/vip-embeddable-tool#199]
The state of Wyoming is attempting to embed the Tool on their webpage, http://soswy.state.wy.us/Elections/PollPlaceLookup%20(2).aspx.

Yesterday, the tool wasn't functioning properly, and in reviewing the page, they have found an error occurring on the back end which indicated they had exceeded the daily request quota for the API.

![image002](https://cloud.githubusercontent.com/assets/7061871/17560640/cd6f8ce0-5ef0-11e6-8db0-9bf1bff28d64.png)

Do you know what's happening here?

**Comment by alexkonrad** [comment]
Looking into this now. Some background: a new Google Maps API policy went
into effect this June requiring an API key for new maps embeds. We added
this key late June / early July and VIP was in talks with Google to
whitelist the key to prevent us from hitting request limits.

Alex Konrad

**Comment by alexkonrad** [comment]
Closing this. We rectified the Maps API issue and are dealing with quota currently.
