### ISSUE TITLE
Adding Karen Language

### ISSUE THREAD

**Issue by lbirdpew** [votinginfoproject/vip-embeddable-tool#200]
Hey team,

Our partner who would like the language installed sent along[ this link](http://my.duniakitab.com/ThanLwinSoft/ThanLwinSoft/MyanmarUnicode/WebDevelopers/) that they used.  I don't know if this helps or not.

**Comment by lbirdpew** [comment]
Any status update?

**Comment by alexkonrad** [comment]
We're still working on getting the web font to display properly in the tool. We will know more and be able to give you a status update later today.

**Comment by lbirdpew** [comment]
Sounds good to me.  I'm OOO for a few days after today so I just wanted to make sure I was touching base on all our projects.  Thanks!

**Comment by alexkonrad** [comment]
Updated. Karen is now one of the language selection options on the tool, as well as a configurable embed option.

**Comment by lbirdpew** [comment]
Awesome, thanks!

**Comment by lbirdpew** [comment]
I see Karen on the drop down, but not on the customizable embed page, am I missing something?
