### ISSUE TITLE
Adjust Default View of Ballot Information from Open to Closed

### ISSUE THREAD

**Issue by lbirdpew** [votinginfoproject/vip-embeddable-tool#202]
Hey Joystick gang,

Can we adjust the default behavior of the ballot information section to have the contests closed when first opened?  This would make it the same as [www.gettothepolls.com](url).  

We think it will increase readablity, especially in places with tons of contests like Washington state.

**Comment by lbirdpew** [comment]
Just bumping this.  Can we get a time estimate on when it might be complete?

**Comment by alexkonrad** [comment]
This is updated.

**Comment by lbirdpew** [comment]
I'm not seeing this on the page.  Address 6330 4th Parallel Rd Ellensburg WA.  Am I being impatient and trying it too soon?  

![image](https://cloud.githubusercontent.com/assets/20073251/19132206/81c66190-8b20-11e6-8eaf-9a261dd41e09.png)

**Comment by alexkonrad** [comment]
Sorry about that. I forgot to invalidate the CloudFront cache.

Here is what I am seeing now:
![image](https://cloud.githubusercontent.com/assets/4000470/19137489/0f4bd768-8b29-11e6-8f72-1a57dc2c7379.png)
