### ISSUE TITLE
JS issue from MTV

### ISSUE THREAD

**Issue by lbirdpew** [votinginfoproject/vip-embeddable-tool#203]
Hey guys,

We just got the below from the developers of MTV's Elect This.  I'm unfamiliar with the specifics of this error.  Can you take a look and let me know if it is something we can do something about?

"We're loading the Javascript file according to the requirements: https://tool.votinginfoproject.org/app.js

This file dynamically inserts a <style> tag into the page, and almost all styles inserted are properly scoped to the #_vit container, however there seems to be a handful of styles that impact elements outside of this container. Specifically, there is a declaration for h1 tags that impacts our global styles:
h1 { font-size: 22px; }

There are a few others near the end (.pac-nudge, .alert_ie, .radio) that should probably be wrapped in the #_vit context as well._"

**Comment by alexkonrad** [comment]
Hi Lester,

Confirming receipt. We should be able to scope these properly for them. Please let me know if you need a timing estimate for this.

**Comment by lbirdpew** [comment]
Hi Alex,

Do we have an idea when this might be resolved?

Thanks!

**Comment by alexkonrad** [comment]
Hi Lester,

We're updating the mentioned fields but we need a little more time to audit the rest of the code base to make sure there aren't any others. We're hoping to have this live by the end of the day today.

**Comment by alexkonrad** [comment]
This is updated. We've wrapped all the styles mentioned. There are a few CSS selectors which we cannot namespace, but we've ensured that those names are prefixed with a `_vit_` namespace to minimize the chance of any collision.
