### ISSUE TITLE
Add officialOnly T/F selection to the customizer

### ISSUE THREAD

**Issue by lbirdpew** [votinginfoproject/vip-embeddable-tool#204]
Add functionality that will allow the user to select whether they want to accept unofficial as well as official data from the Civic Info API.

**Comment by lbirdpew** [comment]
I will add language on here for a blurb to accompany the T/F selection by tomorrow.

**Comment by alexkonrad** [comment]
Thanks Lester.

FYI @laurajoystick as discussed on the call.

**Comment by lbirdpew** [comment]
The accompanying language

Set this parameter to True to return only official state data from the Google Civic Information API. [NOTE: This may result in gaps in coverage due to jurisdictions without official data.]  Set to False to return official AND unofficial data.

**Comment by lbirdpew** [comment]
Also to confirm, the default behavior for the tool is for the parameter to be set to FALSE

**Comment by lbirdpew** [comment]
Hey Alex, do we think this will be ready to deploy this week?

**Comment by lbirdpew** [comment]
Also, please hold on changing the default for officialOnly to FALSE

**Comment by alexkonrad** [comment]
We're working on this one today. We will update the configuration tool field and wait for your go ahead for the parameter.

**Comment by lbirdpew** [comment]
Sounds good.  Let's leave the officialOnly default behavior to TRUE for now.  Is it possible to get instructions telling someone how to manually change it within their code if they don't want to re-embed when the new option goes live.

**Comment by alexkonrad** [comment]
We've added this as a parameter to the customizer tool.

**Comment by lbirdpew** [comment]
Looks good, but can we change the yes/no to true/false?  Then we can close the issue.  Thanks!

**Comment by alexkonrad** [comment]
Hi Lester,

Yep, we can deploy this change along with an update for #218 today.

**Comment by alexkonrad** [comment]
Updated.
