### ISSUE TITLE
Colorado Mail Election Pop Up Page

### ISSUE THREAD

**Issue by lbirdpew** [votinginfoproject/vip-embeddable-tool#205]
Can we please edit the language on the mail election pop up triggered by mail only flag.  See image below.  Here is the text to be added.  The rest of the page should function the same. 
"If you are an active registered voter in Colorado, you will receive a mail ballot.  You can return your ballot by mail, drop off at multiple locations, or vote in person.
Please contact your local election official to learn more about how to receive and return your ballot."

Also please edit the last sentence on the page to read "Please hit continue to see your election information."

Again, this page should be updated for Colorado only.  Thanks!
![image](https://cloud.githubusercontent.com/assets/20073251/19205213/0a3e6722-8caf-11e6-87e9-c2a3fdca5fa6.png)

**Comment by MariaBianchi** [comment]
Hi all! Is there any update on this? The state is asking.

**Comment by alexkonrad** [comment]
Hi @MariaBianchi -- we will have this updated by the end of the day.

**Comment by MariaBianchi** [comment]
Thanks, Alex!

**Comment by alexkonrad** [comment]
Updated. There is currently no `state` field being returned by election 5000, so there is no local election official information appearing.
