### ISSUE TITLE
Referenda do not graphically separate referendum text from the ballot response options

### ISSUE THREAD

**Issue by afsmythe** [votinginfoproject/vip-embeddable-tool#206]
It is difficult to discern between the text of the referendum and the associated ballot responses. 

![screen shot 2016-10-10 at 8 15 53 pm](https://cloud.githubusercontent.com/assets/16374798/19254877/5f12a2c6-8f26-11e6-9b90-b80a794fdb14.png)

Below are the data items returned by the API. The referendumBallotResponses are separated from the referendumText in this example. 

`"ballotPlacement": "902001",
   "referendumTitle": "COUNTY QUESTION A",
   "referendumSubtitle": "Charter Amendment",
   "referendumBrief": "Compilation of Laws",
   "referendumText": "To amend the Anne Arundel County Charter to remove the requirement of recodifying the Anne Arundel County Code at least every ten years.",
   "referendumBallotResponses": [
    "For the Charter Amendment",
    "Against the Charter Amendment"
   ],`

**Comment by lbirdpew** [comment]
The Pew team second this.  If we can add it to our list, it would be great!

**Comment by lbirdpew** [comment]
Is this possible to do?

**Comment by alexkonrad** [comment]
@lbirdpew We can change this today -- should there be any specific messaging surrounding referendum text and responses? We do not have any translated copy for these referendum fields but we could add a header saying "Referendum Responses".

**Comment by lbirdpew** [comment]
I like the "Referendum Responses" text.  Let's do that.  @afsmythe you cool with that?

**Comment by alexkonrad** [comment]
This is updated:

![image](https://cloud.githubusercontent.com/assets/4000470/19669367/add66b5c-9a13-11e6-84ab-71a4c603da38.png)

**Comment by afsmythe** [comment]
Sounds good!
