### ISSUE TITLE
CA Mail Precinct Pop Up

### ISSUE THREAD

**Issue by lbirdpew** [votinginfoproject/vip-embeddable-tool#207]
For mail only precincts in California, can we adjust the pop up to be something like this:

"Mail-Only Precinct

For the upcoming election, your precinct is mail-only. If you have questions, you can contact your local election official:

ELECTION OFFICIAL INFO

This also means you may be able to return your ballot at multiple locations. Please hit continue to see your election information."

**Comment by lbirdpew** [comment]
This would only be for the mail-only precincts in California

**Comment by alexkonrad** [comment]
Updated. Do you have a list of mail-only precincts in California to verify?

Currently election 5000 does not have a `state` field so no local election official information will appear.
