### ISSUE TITLE
High Priority: Set API electionId to 5000

### ISSUE THREAD

**Issue by lbirdpew** [votinginfoproject/vip-embeddable-tool#210]
Due to an issue with the civic info api, we need to set the electionId to 5000 instead of leaving it blank as is the current standard.  After the election, we will need to remove this Id.

**Comment by alexkonrad** [comment]
@lbirdpew I think it makes the most sense to set 5000 as the default id and still allow individual embeds to override that if they choose, for example to pull from a testing election. Let me know if you disagree.

**Comment by lbirdpew** [comment]
@alexkonrad That works for me.

**Comment by alexkonrad** [comment]
Election ID is now set to 5000 by default.
