### ISSUE TITLE
Alpha sort languages after English and Spanish

### ISSUE THREAD

**Issue by lbirdpew** [votinginfoproject/vip-embeddable-tool#211]
Can we alpha sort the languages after English and Spanish?  So English, Spanish, all other languages alpha sorted.  Currently, Japanese and Karen are mis-sorted.

**Comment by alexkonrad** [comment]
Updated.
![image](https://cloud.githubusercontent.com/assets/4000470/19502429/b18ef5ea-9561-11e6-8d66-c5dba6a6c62c.png)
