### ISSUE TITLE
Urgent - Polling Location Hours shown w/ Early Vote Site Dates in Multiple Service Location block

### ISSUE THREAD

**Issue by MariaBianchi** [votinginfoproject/vip-embeddable-tool#213]
![co example](https://cloud.githubusercontent.com/assets/7061871/19500134/80e433c2-9568-11e6-87bd-425e001734c2.jpg)
 The tool correctly identifies a location as offering both early and election day voting. The tool also displays the voter services and start/end dates for the early voting site. However, the only voting hours being displayed are those for Election Day voting, those associated with the polling location object, though that isn't noted. The location pictured below, like many that offer early and day-of voting, is open at different times during early voting than it is on election day.

In this case, the early voting hours should be "8AM - 5PM Mon-Fri; 9AM - 2PM Saturday; 7AM - 7PM Election Day" per the data provided by the state. Ideally, since we're displaying the early vote start/end dates, we should prefer the hours object from the early vote site.

![co example](https://cloud.githubusercontent.com/assets/7061871/19500144/8d4e217c-9568-11e6-93eb-9a3303b1221d.jpg)

![screen shot 2016-10-18 at 7 26 21 pm](https://cloud.githubusercontent.com/assets/7061871/19500171/cae56d06-9568-11e6-9406-f5daf917a3cb.png)

@lbirdpew

**Comment by alexkonrad** [comment]
@MariaBianchi We can incorporate this. Is this a different election ID from 5000? I am only seeing early vote sites in the response for that address.

**Comment by MariaBianchi** [comment]
No, that's EID 5000, but the data isn't live yet - the picture is from our
staging implementation. (Google has unofficial data for early voting that
is being returned in the live tool.



Maria Bianchi
Project Manager | Voting Information Project
Democracy Works
maria@*democracy.works* <maria@democracy.works>
(o): 718-923-1400 ext. 3000 | (c): 716-908-5617

**Comment by alexkonrad** [comment]
@MariaBianchi would something like this work?
![image](https://cloud.githubusercontent.com/assets/4000470/19501028/145da3c0-9557-11e6-9981-34adf6cbf0c9.png)
This way we won't overwrite information (e.g., polling hours) from the voting location but instead just prepend "Election Day Voting Hours" and include "Early Voting Hours" (before or after).

**Comment by MariaBianchi** [comment]
That would be perfect!

Maria Bianchi
Project Manager | Voting Information Project
Democracy Works
maria@*democracy.works* <maria@democracy.works>
(o): 718-923-1400 ext. 3000 | (c): 716-908-5617

**Comment by alexkonrad** [comment]
@MariaBianchi updated. Instead of "Election Day Voting Hours" I kept "Voting Hours" as the default and any additional location type hours will be "Early Voting Hours" or "Drop-off Location Hours." Let me know if we need to adjust this further.
