### ISSUE TITLE
New To GitHub

### ISSUE THREAD

**Issue by IronSara** [votinginfoproject/vip-embeddable-tool#216]
Hi, I am trying to put this script on to a NationBuilder site, but I get an error when using it. I am not sure how to go about troubleshooting this.

https://cloud.githubusercontent.com/assets/5118973/19503713/5e564b36-956a-11e6-859b-4c30207fbcca.JPG

**Comment by codealchemy** [comment]
@IronSara welcome to Github! In using the widget on a NationBuilder page of my own I ran into the same issue with the address in your screenshot - updating the widget to set `officialOnly` to `false`, however, returned some results. According to the [params docs](https://github.com/votinginfoproject/vip-embeddable-tool#parameters) this allows for data to be returned from _unofficial_ election sources - in more detail:

>Set this parameter to True to return only official state data from the Google Civic Information API. [NOTE: This may result in gaps in coverage due to jurisdictions without official data.] Set to False to return official AND unofficial data. ([source](https://s3.amazonaws.com/vip-voter-information-tool/cms/index.html))

The full script that I used was:

```html
<script type="text/javascript" src="https://tool.votinginfoproject.org/app.js"></script>
<div id="_vit"></div>
<script type="text/javascript">vit.load({officialOnly: false});</script>
```

Hope this helps!

**Comment by IronSara** [comment]
Wow - that worked! Thank you so much for making this so easy. I know only a bit of HTML/CSS and I was able to include it on my website. Great work!

**Comment by lbirdpew** [comment]
Hi @IronSara, also set the electionId to 5000 to return more results.  Currently, we don't have official data live in Arizona, but we do have some unofficial data live.  Setting officialOnly to FALSE allows you to see official and unofficial data.  Setting the electionId to 5000 helps square away a bug we sometimes have with the unofficial data.  

Hope this helps!
