### ISSUE TITLE
VERY URGENT: Pins not loading in VIT

### ISSUE THREAD

**Issue by MariaBianchi** [votinginfoproject/vip-embeddable-tool#217]
It appears that something may have broken, because I'm no longer seeing the marker pins loading in any version of the tool.

Test addresses w/ live data: 874 BUCK MOUNTAIN RD DOE RUN MO 63637
5028 37th Ave NE, Seattle, WA 98105

![screen shot 2016-10-18 at 10 55 07 pm](https://cloud.githubusercontent.com/assets/7061871/19504198/4f9255ce-9586-11e6-9b0a-8ff38d196a41.png)

@alexkonrad

**Comment by alexkonrad** [comment]
@MariaBianchi Thanks for flagging this so quickly. Expanding the bounds around the closest 5 drop pins won't work for single-pin locations and will cause an error with Google Maps. I'm updating this right now.

**Comment by alexkonrad** [comment]
Updated.
![image](https://cloud.githubusercontent.com/assets/4000470/19505210/9df7aa68-9575-11e6-93e4-cdc4b5cc88dd.png)
Henceforth we will wait for confirmations of new features in the staging area to help us catch any bugs that we haven't in the deployment process. Please let me know if there are any more issues tonight.
