### ISSUE TITLE
Support Request 2

### ISSUE THREAD

**Issue by lbirdpew** [votinginfoproject/vip-embeddable-tool#218]
Received this request from a place trying to embed.  Can we help from this?  Or do I need to get more?

----------------------------------------------------------------------------
Hi the code we downloaded isn’t running when we embed it. 
 
Any help for that?

This is the code:
 
```
<script type="text/javascript" src="https://tool.votinginfoproject.org/app.js"></script>
<div id="_vit"></div>
<script type="text/javascript">vit.load({
    modal: true,
    title: 'Get out and vote!',
 
    logo: 'https://d1qkyo3pi1c9bx.cloudfront.net/D7021408-671F-42FA-837E-DEB20A6B3D76/9e8423b8-f390-429a-9d4c-58cfb8444782.jpg',
    colors: {
      'header': '#000',
      'landscapeBackgroundHeader': '#555'
    },
    language: 'en',
});</script>
```
 
This is the page: 
 
http://www.liunaforhillary.org/get-out-and-vote

**Comment by alexkonrad** [comment]
Updated. A Javascript library on an embedding page was causing conflicts with our code. We added an extra wrapper.
