### ISSUE TITLE
Not getting any data in Texas?

### ISSUE THREAD

**Issue by markcorcoran** [votinginfoproject/vip-embeddable-tool#219]
I keep testing this with addresses in Texas. But not getting any results right now. 

Is it just not available yet, or am I doing something very wrong?

**Comment by lbirdpew** [comment]
Hi Mark, official TX data is not yet available.  When you customize the widget, select False for the API parameter officialOnly to return official and unofficial data.  Currently, we have EV sites available in TX when looking at unofficial data.
