### ISSUE TITLE
Instructions for Manually Changing officialOnly Call on Embedded Widget

### ISSUE THREAD

**Issue by lbirdpew** [votinginfoproject/vip-embeddable-tool#224]
Hey Alex,

Can I get a quick guide on how to change the officialOnly call after you've already embedded the widget?  

-Lester

**Comment by alexkonrad** [comment]
Hi Lester,

You need to reembed the widget with the `officialOnly` parameter set to true:

```html
<script type="text/javascript" src="https://tool.votinginfoproject.org/app.js"></script>
<div id="_vit"></div>
<script type="text/javascript">vit.load({
  officialOnly: true
});</script>
```

Let me know if you need any other information!

**Comment by lbirdpew** [comment]
You'd want False, though since true is the default.  Thanks!
