### ISSUE TITLE
Urgent officialOnly

### ISSUE THREAD

**Issue by lbirdpew** [votinginfoproject/vip-embeddable-tool#225]
Hey Alex,

When you customize the widget, selecting false does not set officialOnly to False, it leaves it blank.  Blank defaults to True.  Setting it to true does add true after officialOnly in the embed code.  Can we change the embed code so that setting False adds False after officialOnly?

**Comment by alexkonrad** [comment]
Fixed. Customizer now shows `officialOnly: true` by default and `officialOnly: false` otherwise.

**Comment by lbirdpew** [comment]
Perfect

**Comment by lbirdpew** [comment]
I'm not seeing it on the customizer page yet though

**Comment by alexkonrad** [comment]
@lbirdpew Sorry -- the CloudFront CDN takes about 10 minutes to refresh. I'm seeing it in a incognito window. Can you check again?

**Comment by lbirdpew** [comment]
Perfection!
