### ISSUE TITLE
Tech Support - Problems embedding in Wordpress

### ISSUE THREAD

**Issue by lbirdpew** [votinginfoproject/vip-embeddable-tool#226]
Hey gang,

A client is having problems embedding the widget in wordpress.  Below is their message to me.

No results-I get two little boxes like this, but no widget..I tried inserting code in text editor and then as an html snippet, but neither method worked. I’m not a wordpress expert so go easy on me with instructions on hwo to make this thing work!

![image](https://cloud.githubusercontent.com/assets/20073251/19772271/ad2f5e26-9c33-11e6-9984-ef9a3a495dc9.png)

```
`<script type="text/javascript" src="https://tool.votinginfoproject.org/app.js"></script>
<div id="_vit"></div>
<script type="text/javascript">vit.load({
    modal: true,
    theme: 'https://tool.votinginfoproject.org/images/theme3.png',
    officialOnly: true,
    title: 'Women's Equity Center',
    subtitle: 'and Action Network',

    colors: {
      'header': '#ffa004',
      'landscapeBackgroundHeader': '#dd8004'
    },
    language: 'en',
});</script>
`
```

**Comment by alexkonrad** [comment]
Hi @lbirdpew,

A few troubleshooting questions for the client:

1. Can you remove the backtick characters surrounding the code? The embed code should look like this:

```html
<script type="text/javascript" src="https://tool.votinginfoproject.org/app.js"></script>
<div id="_vit"></div>
<script type="text/javascript">vit.load({
    modal: true,
    theme: 'https://tool.votinginfoproject.org/images/theme3.png',
    officialOnly: true,
    title: 'Women's Equity Center',
    subtitle: 'and Action Network',

    colors: {
      'header': '#ffa004',
      'landscapeBackgroundHeader': '#dd8004'
    },
    language: 'en',
});</script>
```

2. Is the user account that you're writing the post with an admin or editor account? Only admin or editor user accounts are able to add HTML code to posts in WordPress.

If these do not work, it will be helpful to know where it's hosted for further troubleshooting:

3. Where is this WordPress site hosted? Is it hosted by wordpress.com, or another provider?

**Comment by lbirdpew** [comment]
No response
