### ISSUE TITLE
Urgent: White screen for certain polling location searches?

### ISSUE THREAD

**Issue by MariaBianchi** [votinginfoproject/vip-embeddable-tool#228]
![screen shot 2016-11-02 at 4 47 11 pm](https://cloud.githubusercontent.com/assets/7061871/19946868/0baac67e-a11c-11e6-9cc9-597c836e36cc.png)

**Comment by MariaBianchi** [comment]
For the searched address, 137 Oleander Rd., Morenci, AZ 85540, the API returns polling location Vc1 Voting Center-1
Morenci Club Morenci Az.
Morenci Plaza
Morenci, AZ 85540

So I'm not sure what's happening here.

**Comment by lbirdpew** [comment]
This is on the staging server

**Comment by alexkonrad** [comment]
@lbirdpew @MariaBianchi can you provide the election ID?

**Comment by MariaBianchi** [comment]
EID 5000

Maria Bianchi
Project Manager | Voting Information Project
Democracy Works
maria@*democracy.works* <maria@democracy.works>
(o): 718-923-1400 ext. 3000 | (c): 716-908-5617

**Comment by alexkonrad** [comment]
@MariaBianchi This is happening because the Geocoder is actually not able to parse this address:

![image](https://cloud.githubusercontent.com/assets/4000470/19951245/e477f90c-a119-11e6-8e16-cc861e1265c2.png)

Two options for addressing this are:

1. Add additional rules for the tool to massage the address before sending it to be geocoded
2. Add error conditions to skip geocoding this address if the geocoder is unsuccessful.

**Comment by MariaBianchi** [comment]
@lbirdpew What would you prefer? A white screen with no information returned seems like a particularly bad handling of this.

What would it look like to the user if we skipped geocoding when it failed?

**Comment by alexkonrad** [comment]
@MariaBianchi The location will be displayed but it's position will be no more accurate than its zip code. I am implementing that in the tool now because we need to be able to pass over these malformed location addresses to continue the functioning of the tool.

**Comment by MariaBianchi** [comment]
Thanks!

Maria Bianchi
Project Manager | Voting Information Project
Democracy Works
maria@*democracy.works* <maria@democracy.works>
(o): 718-923-1400 ext. 3000 | (c): 716-908-5617

**Comment by alexkonrad** [comment]
The tool is updated to skip locations that cannot be geocoded.

![image](https://cloud.githubusercontent.com/assets/4000470/19954588/aae55532-a136-11e6-88b4-4030f1b25d11.png)

**Comment by lbirdpew** [comment]
Thanks everyone.
