### ISSUE TITLE
Rename 'Referendum Responses'

### ISSUE THREAD

**Issue by afsmythe** [votinginfoproject/vip-embeddable-tool#231]
A few states have requested this title be renamed to something more broad, such as 'Responses'.

![image002](https://cloud.githubusercontent.com/assets/16374798/22252311/bd5a8450-e21b-11e6-890f-af8d51387545.png)

**Comment by lbirdpew** [comment]
We support this request as not every state calls ballot measures "referendums."  @alexkonrad is this an easy fix?

**Comment by alexkonrad** [comment]
Updated.
