### ISSUE TITLE
Embeddable tool shows a blank square

### ISSUE THREAD

**Issue by afsmythe** [votinginfoproject/vip-embeddable-tool#233]
To Reproduce: Go to the VIT staging site.
Enter `2268 Shadowlake Court Virginia Beach VA 23454` and select the June election. In the console, you should see a JS exception.

With Chrome Developer tools enabled, the VIP API does confirm a polling location result, but no information is displayed in the frame. 

<img width="1259" alt="screen shot 2017-04-17 at 4 36 37 pm" src="https://cloud.githubusercontent.com/assets/16374798/25354690/f8092872-2901-11e7-87d7-3923405fd2fc.png">

**Comment by afsmythe** [comment]
Pinging @lbirdpew.

**Comment by lbirdpew** [comment]
Thanks @afsmythe, @alexkonrad could you take a look and let us know what you think.  The same error also occurs on the regular site when you select the June election, not just on the staging site.

**Comment by alexkonrad** [comment]
Lester, will do ASAP

**Comment by lbirdpew** [comment]
Sounds good, thanks Alex

**Comment by alexkonrad** [comment]
@lbirdpew This is fixed. Entering `2268 Shadowlake Court Virginia Beach VA 23454` should return data for either election.

**Comment by lbirdpew** [comment]
@alexkonrad Thanks!
