### ISSUE TITLE
Accessibility Issues with Voting embedded tool

### ISSUE THREAD

**Issue by KevinCourtney** [votinginfoproject/vip-embeddable-tool#234]
Hello - We are using the Voting Information embed tool on our site and we received notification that the tool had an accessibility issue.

I have done a full review of the tool and found multiple issues that would prevent keyboard only users and visual impaired users from accessing voting location information.

Have you been made aware of these issues? I can provide details of my review, if there is a resource that could fix the tool.   Thank you.

**Comment by lbirdpew** [comment]
Hi Kevin,

If you could provide the review it would be incredibly helpful. My email is lbird@pewtrusts.org.  We will be redesigning the widget this summer so your feedback will be incredibly helpful.

-Lester

**Comment by KevinCourtney** [comment]
Thank you, Lester. I've emailed you the report.

Kevin
