### ISSUE TITLE
Make Polling Location icon in legend  "clickable"

### ISSUE THREAD

**Issue by jen-tolentino** [votinginfoproject/vip-embeddable-tool#51]
When viewing both early vote and the main polling location, it would be great if clicking on the polling location icon, or clicking on the tab, refreshed the screen to the main polling place.

**Comment by alexkonrad** [comment]
I updated this for polling locations. We may have to do something differently for EV sites and drop-off locations depending, let me know what you think.

**Comment by jen-tolentino** [comment]
Thanks Alex. This looks good. For EV sites and drop-off, I think it makes sense to link to them to the option closest to the registered address, which would be the first result. Does that sounds feasible?

**Comment by alexkonrad** [comment]
Updated on staging.

**Comment by alexkonrad** [comment]
@jen-tolentino are there addresses on 4100 that can pull EV sites, dropoff locations, etc. currently? Or maybe in another election?

**Comment by jen-tolentino** [comment]
I tested it for drop boxes using this address w/4100: 13698 SW Aerie Dr, Tigard, OR 97223

Clicking on the icon multiple times makes it shuffle through the list.
