### ISSUE TITLE
Make it possible to close/minimize the polling location info bubble

### ISSUE THREAD

**Issue by jen-tolentino** [votinginfoproject/vip-embeddable-tool#52]
It would be helpful if a user could close the info bubble the pops up on the map. Click on the icon would then bring it up again.

**Comment by alexkonrad** [comment]
Updated (made the close icon persistent)

**Comment by jen-tolentino** [comment]
Thanks Alex! The icon I am seeing in Firefox and Chrome is a square (see below). Could you make it something more obvious, like an 'X'?

![image](https://cloud.githubusercontent.com/assets/5825049/7454503/3e1a8df4-f242-11e4-8ce7-d709b2a3640a.png)

**Comment by alexkonrad** [comment]
Updated.
