### ISSUE TITLE
Add phone numbers to the contact

### ISSUE THREAD

**Issue by jen-tolentino** [votinginfoproject/vip-embeddable-tool#73]
When available in the API, can we include phone number for in the contact information? I believe DE has this in its feed. Thanks!

![image](https://cloud.githubusercontent.com/assets/5825049/4629592/f007fa9c-53a5-11e4-91e7-f9db5448bb91.png)

**Comment by jen-tolentino** [comment]
The live Michigan election has this in its live feed right now for local election officials:

1893 W TRASK LAKE RD BARTON CITY MI 48705

@alexkonrad

**Comment by alexkonrad** [comment]
Great, thanks!

Alex Konrad

**Comment by alexkonrad** [comment]
This is updated.

**Comment by jen-tolentino** [comment]
Looks good!

**Comment by alexkonrad** [comment]
Closing this because the email/phone modifications we discussed are in another issue (#119).
