### ISSUE TITLE
Suppress duplicate addresses

### ISSUE THREAD

**Issue by jen-tolentino** [votinginfoproject/vip-embeddable-tool#77]
If the physical address and correspondence address is the same, can we suppress one of them and the title? Meaning, we'd only surface the address, no disclaimer on whether its for correspondence or physical.

![image](https://cloud.githubusercontent.com/assets/5825049/4653301/ae7ad6d2-54ac-11e4-8a3c-1b1585f9c194.png)

**Comment by alexkonrad** [comment]
Updated on staging. I removed the "Correspondence/physical address" markers.

**Comment by jen-tolentino** [comment]
Looks good, thanks! Please push to production.
