### ISSUE TITLE
Suppress duplicate links

### ISSUE THREAD

**Issue by jen-tolentino** [votinginfoproject/vip-embeddable-tool#78]
DC is a special case, but this might also show up in other feeds. It would be great to suppress any duplicate links, surfacing them under state.

![image](https://cloud.githubusercontent.com/assets/5825049/4653409/9426d1c2-54ad-11e4-9526-2dd63269ac92.png)

**Comment by alexkonrad** [comment]
This is updated on staging. For this address (1629...) some of the links are very similar but not quite duplicates so haven't been removed.

**Comment by jen-tolentino** [comment]
Great, thanks! Please push to production.
